### ISSUE TITLE
Apply XDG base directory specifications for configuration files

### ISSUE THREAD

**Issue by z0rc** [deskflow/deskflow#5762]
### Operating Systems ###

Server: Windows 10
Client: Kubuntu 16.10

### Synergy Version ###

1.8.6-rc1-d0db743

### Steps to reproduce bug ###

1. Set connect to server with SSL enabled

### Other info ###

* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

Synergy creates unnecessary top level dotdir with SSL configuration in it. Please use $XDG_CONFIG_HOME (with fallback to ~/.config) for storing such data. More at https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by adrianinsaval** [comment]
@nbolton this is still a problem in deskflow, it should probably default to .local/share/deskflow

**Comment by sithlord48** [comment]
`~/.config` .. would be the place for this .

**Comment by adrianinsaval** [comment]
sounds good, can you reopen the issue since it's not actually fixed yet?

**Comment by nbolton** [comment]
Personally I'm not happy that our config files are spread around a few different places.

This is good:
```
$ ls ~/.config | grep Deskflow
Deskflow
```

This is not:
```
$ ls -R ~/.synergy/
~/.synergy/:
SSL

~/.synergy/SSL:
Fingerprints  Synergy.pem

~/.synergy/SSL/Fingerprints:
Local.txt  TrustedServers.txt
```

**Comment by sithlord48** [comment]
@nbolton pleas make pr for this we should not be looking in `~/.deskflow` at all for sure

**Comment by nbolton** [comment]
> @nbolton please make pr for this we should not be looking in `~/.deskflow` at all for sure

On it: #7685
