### ISSUE TITLE
Extra mouse buttons

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#58]
**Imported issue:**
- Author: nick.bolton.uk (Google user)
- Date: 2009-05-24 00:00:00
- Legacy ID: 67

It looks like some users are having trouble using additional mouse buttons  
such back and forward, etc. I know from experience that mouse buttons can  
have an array of extra buttons, which some users do make use of.  

From user, Id:  
"http://groups.google.com/group/synergy-":http://groups.google.com/group/synergy-  
plus/browse_thread/thread/015cb5e4da7d7ed4  

Is there a way to get the mouse buttons (back and forward on the side  
of the mouse) to work using synergy?   

I am using a Windows synergy server and a Ubuntu client.   

Also, when I press a keyboard button and keep it pressed, the key is  
not sent several times afterwards. For example, while editing this  
text, if I put my cursor at the end, then press backspace (and keep it  
pressed), only one letter will be erased.

**Comment by keab42** [comment]
I have a Microsoft mouse with the forward and back buttons. I'm using a Mac as the server with the intellipoint drivers to get them working correctly, however Synergy is mapping them oddly to the windows client. Instead of acting as back and foward, they seem to act to snap windows to the side of the screen. What mappings do I need to make to correct this?

**Comment by nkoroste** [comment]
Same issue.
Logitech G500s
Server: Ubuntu 14.04
Client: OS X 10.10.5

**Comment by noscript** [comment]
Doesn't work for me either. Tried Logitech MX Master and Logitech Performance MX.

Host: Debian
Guest: Windows
Synergy 1.7.4

**Comment by Lihis** [comment]
Does not work here either. Back and forward buttons does nothing. Mouse is SteelSeries Rival.

Host: Arch Linux
Guest: Windows 10
Synergy: 1.7.5

However, got the buttons working by adding this to Synergy server configuration in the section: options
```
mousebutton(6) = mousebutton(4)
mousebutton(7) = mousebutton(5)
```

**Comment by noscript** [comment]
> However, got the buttons working by adding this to Synergy server configuration in the section: options

It will not work with config file generated by wizard, it uses a completely a different format.

That's how mapping mouse button 4 to 4 generated:
```
hotkeys\2\keys\1\key=5
hotkeys\2\keys\size=1
hotkeys\2\actions\1\keys\1\key=5
hotkeys\2\actions\1\keys\size=1
hotkeys\2\actions\1\type=2
hotkeys\2\actions\1\typeScreenNames\size=0
hotkeys\2\actions\1\switchScreenName=debian
hotkeys\2\actions\1\switchInDirection=0
hotkeys\2\actions\1\lockCursorToScreen=0
hotkeys\2\actions\1\activeOnRelease=false
hotkeys\2\actions\1\hasScreens=false
hotkeys\2\actions\size=1
```

But I counln't figure out how to map 6 to 4, seems any higher number than 5 in `key=5` is being ignored.

**Comment by KaptenJansson** [comment]
I managed to get the back and forward mouse buttons to work on Mac OS by doing:
```
	mousebutton(6) = keystroke(meta+left,nameOfMac)
	mousebutton(7) = keystroke(meta+right,nameOfMac)
```

You can omit `nameOfMac` if you only have Mac OS as clients.

**Comment by strank** [comment]
To add another data point, this here worked for me:
Synergy 1.8.2 Host: Ubuntu Guest: Mac

In synergy.conf::
```
	mousebutton(6) = keystroke(Meta+[,macname)
	mousebutton(7) = keystroke(Meta+],macname)
```

In Ubuntu the back and forward buttons on the Logitech mouse are recognized as 4 and 5, also in the synergy UI for hotkeys. But only assigning 6 and 7 in the config file results in input events on the Mac side. Configuring through the UI is therefore not possible.

I'm not sure how this switch happens, but it seems that the button numbering changes when the focus switches to the other machine.

**Comment by nkoroste** [comment]
Can confirm on Synergy 1.8.4 mousebutton(6) and mousebutton(7) work for me as well. Server Ubuntu Client MacOsx

**Comment by paul-suarez** [comment]
Author: mjkalba
Date: 05/04/17 at 10:24 PM

I don't know if something changed with the latest update to Windows 10 Creators Update
(Build 15063.rs2_release.170317-1834), but synergy no longer seems to be
passing my mouse identification through to the client systems.

I have a Microsoft Wireless Laser Mouse 8000, with additional (left and
right side) buttons. I am no longer able to use these on the client systems.

I am running Synergy 1.88-stable.c30301e
I have 3 systems currently active, all running the same version of WIndows and Synergy as specified above.
Looking in the server log file, if I press either of the 2 additional side buttons, they both produce:

[2017-05-05T15:46:36] DEBUG1: event: button press button=0
[2017-05-05T15:46:36] DEBUG1: event: button release button=0

The normal left and right buttons have values of 1 and 3

**Comment by BarrettStephen** [comment]
I have the same issue. as Paul, above. Same versions. 
Host is the windows box, client is ubuntu 16.04.

**Comment by zelivans** [comment]
Joining @BarrettStephen, the issue persists with the same versions

**Comment by samuelba** [comment]
Same problem as @paul-suarez 
Server Windows 10
Client Ubuntu 16.04

I get this for both buttons (forward/back)

[2017-06-21T21:56:25] DEBUG1: event: button press button=0
[2017-06-21T21:56:25] DEBUG1: event: button release button=0

**Comment by AdrianSkar** [comment]
> Does not work here either. Back and forward buttons does nothing. Mouse is SteelSeries Rival.
> 
> Host: Arch Linux
> Guest: Windows 10
> Synergy: 1.7.5
> 
> However, got the buttons working by adding this to Synergy server configuration in the section: options
> 
> ```
> _mousebutton(6) = mousebutton(4)_
> mousebutton(7) = mousebutton(5)
> ```

This seems to work for me under version 1.10.1-stable
Server : Xubuntu 18.04.2
Client: Windows 10
Mouse: Roccat Nyth using 7 as Browser backwards (configured through the app).

**Comment by audunlh** [comment]
> > Does not work here either. Back and forward buttons does nothing. Mouse is SteelSeries Rival.
> > Host: Arch Linux
> > Guest: Windows 10
> > Synergy: 1.7.5
> > However, got the buttons working by adding this to Synergy server configuration in the section: options
> > ```
> > _mousebutton(6) = mousebutton(4)_
> > mousebutton(7) = mousebutton(5)
> > ```
> 
> This seems to work for me under version 1.10.1-stable
> Server : Xubuntu 18.04.2
> Client: Windows 10
> Mouse: Roccat Nyth using 7 as Browser backwards (configured through the app).

Same here, version 1.11.1-stable
Server: 18.04.4 LTS (Bionic Beaver)
Client: Windows 10 Enterprise, build 17763
Mouse: Logitech M-U0007

**Comment by jenga201** [comment]
Leaving this comment so search for this the next time is easier.

```
section: options
        mousebutton(4) = keystroke(alt+left)
        mousebutton(5) = keystroke(alt+right)
end
```

**Comment by zack09holland** [comment]
@jenga201 thank you! That was the one that worked for me.
server: Windows 11
client: Ubuntu 22.04

**Comment by vinozganic** [comment]
Has any of you got it working for combination:
Server: MacOS, Client: Windows

None of the combinations for options section in config worked for me...
I need my additional page back and page forward keys to work :(

**Comment by dkniffin** [comment]
This is still present on Synergy 3.0.80.1-rc3, and the workarounds above don't seem to work. My host is Linux Mint, and client is MacOS

I also did some digging and I think I found the cause. 

Looking at a debug 2 log, I see:
```
synergy-core     [2024-10-16T15:50:54] - DEBUG1  - recv mouse down id=7
synergy-core     [2024-10-16T15:50:55] - DEBUG1  - recv mouse up id=7
synergy-core     [2024-10-16T15:50:55] - DEBUG1  - recv mouse down id=6
synergy-core     [2024-10-16T15:50:55] - DEBUG1  - recv mouse up id=6
synergy-core     [2024-10-16T15:50:56] - DEBUG1  - recv mouse down id=7
synergy-core     [2024-10-16T15:50:57] - DEBUG1  - recv mouse up id=7
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - recv mouse down id=1
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - faking mouse button id: 0 press: pressed
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - recv mouse up id=1
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - faking mouse button id: 0 press: released
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - recv mouse down id=1
synergy-core     [2024-10-16T15:51:00] - DEBUG1  - faking mouse button id: 0 press: pressed
synergy-core     [2024-10-16T15:51:01] - DEBUG1  - recv mouse up id=1
```
`recv mouse down id=7` is mouse back, `recv mouse down id=6` is mouse forward, `recv mouse down id=1` is left click. So it looks like it is receiving the clicks, but it's not doing `faking mouse button...` for the 6 and 7 presses.

From what I can tell, the `faking` output comes from [here](https://github.com/deskflow/deskflow/blob/52f616a15d094bb3ba7ec30a2a04b764f7b2bf22/src/lib/platform/OSXScreen.mm#L588). Looking around there, I see [this line](https://github.com/deskflow/deskflow/blob/52f616a15d094bb3ba7ec30a2a04b764f7b2bf22/src/lib/platform/OSXScreen.mm#L542), which returns early if `index >= NumButtonIDs`. `NumButtonIDs` is defined as `5` [here](https://github.com/deskflow/deskflow/blob/da6b3942ae7f9cd284ff0195ab50fbce63edabee/src/lib/deskflow/mouse_types.h#L42).

@nbolton Would you accept a PR to change this? I have basically no CPP experience, and I don't know how to compile the library to test this change, but I feel pretty confident this will fix the issue.

**Comment by nbolton** [comment]
> @nbolton Would you accept a PR to change this variable to 7? I have basically no CPP experience, and I don't know how to compile the library to test this change, but I feel pretty confident this will fix the issue.

Sure, it's worth a try. It'd be a Deskflow build, but you'll be able to grab a package from CI artefacts.

**Comment by dkniffin** [comment]
PR: https://github.com/deskflow/deskflow/pull/7718

I'll wait for it to build and see if I can get an installable package to test with

**Comment by dkniffin** [comment]
That didn't fix the issue, but I think it's along the right track. But I don't have time to troubleshoot it more.

However, I did figure out that this config in Synergy now fixes the issue for me:

```
        mousebutton(6) = mousebutton(4)
        mousebutton(7) = mousebutton(5)
```

I could've sworn I tried that before and it didn't work, but it seems to now :man_shrugging:

**Comment by alexfornuto** [comment]
I have this issue with my Keychron mouse, the horizontal scroll wheel is interpreted as the back/forward button on the client.

Linux server, Windows client, Deskflow 1.24.0. 

P.S. Is the syntax above still correct for current Deskflow configs? Would `section: options` be `[options]`?

P.P.S. When using the flatpack, is it not possible to use a custom config file?

**Comment by sithlord48** [comment]
the config in question is the server config. and yes you can use it w/ the flatpak flatpak files are usually in ~/.var/lib/flatpak or some variation of that , when you start the gui the log will tell you where the settings files are located.

**Comment by alexfornuto** [comment]
@sithlord48 thanks for that! I found the file and am trying to add the remapping, but each time I re-open deskflow it rewrites my parenthesis as:

```
[options]
mousebutton%286%29=mousebutton(8)
mousebutton%287%29=mousebutton(9)
```

**Comment by sithlord48** [comment]
copy the file out and try using the external config option in the server config. When you are not using this the gui "generates" a server config based on it settings .

**Comment by alexfornuto** [comment]
Thanks, I was modifying the wrong file (should have know due to the change of syntax). Now I'm just trying to figure out what to map my horizontal wheel buttons to that a Windows client will recognize as left and right, not back and forward.
