### ISSUE TITLE
Not working on multiple X screens

### ISSUE THREAD

**Issue by dsprince** [deskflow/deskflow#5956]
Server: Ubuntu 16.04
Client: Windows 7, and Ubuntu 14.04 (but probably not relevant.)
Synergy Versions: 1.8.5 - 1.8.8 (at least)

The synergy server randomly intermittently) transfers control to the client when the mouse pointer gets to the edge of any X screen, not the edge of the whole desktop. This makes synergy unpredictable and hard to use.

The server's screen setup is four monitors in a horizontal row, split over three X screens (the middle two are merged into :0.0 with a single monitor to the left serving :0.1 and another to the right serving :0.2.

The synergy setup I have has the windows client to the left of the server desktop, and the other Linux machine to the right.

The problem is, e.g., that the server will switch control to the windows client when the pointer is moved to the left of monitor 1 (that's fine.) It also _sometimes_ switches when moving to the left of monitors 2 and 4 (i.e. the left hand extents of the X screens.) This makes it pot luck as to whether I can access all of my server desktop when synergy is running.

My workaround at the moment is to shut the synergy server down unless I want to use one of the other machines. This is okay until I'm in a situation where I need to use both at once - that becomes rather confusing/frustrating.

Before I spend time trying to log the details etc., please can you say whether this should be supported? (I had an older setup that was similar, but not exactly the same, running a much older version of synergy and Ubuntu, and that seemed to work okay.)

**Comment by nlyan** [comment]
Yes, this should be supported. This is most likely a XrandR bug.

**Comment by dsprince** [comment]
Hmmm, okay. I'm not knowingly using XrandR. The display setup was done using nvidia-settings and getting it to write an xorg.conf. The screens are laid out in the config like this:

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 1600 0
    Screen      1  "Screen1" 0 240
    Screen      2  "Screen2" 3700 328
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

and the xrandr commandline query describes the screens and monitors like this:

11:27-amazon:~> xrandr --display :0.0
Screen 0: minimum 8 x 8, current 2100 x 1680, maximum 16384 x 16384
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1050x1680+1050+0 left (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 connected primary 1050x1680+0+0 left (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-6 disconnected (normal left inverted right x axis y axis)
11:27-amazon:~> 
11:27-amazon:~> 
11:27-amazon:~> xrandr --display :0.1
Screen 1: minimum 8 x 8, current 1600 x 1200, maximum 16384 x 16384
DP-7 connected primary 1600x1200+0+0 (normal left inverted right x axis y axis) 367mm x 275mm
   1600x1200     60.00*+
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
11:27-amazon:~> 
11:27-amazon:~> 
11:27-amazon:~> xrandr --display :0.2
Screen 2: minimum 8 x 8, current 1280 x 1024, maximum 16384 x 16384
DP-3 connected primary 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1280x960      60.00  
   1152x864      75.00    70.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
11:27-amazon:~>

The offsets and rotations etc. all look like they add up correctly to me, so what do you think the bug is here?

Also, with a bit more testing I've determined a few more details of the weirdnesses and inconsistencies:

- Control will sometimes switch to the left client when moving to the left hand side of the server's right most, and central screens (it becomes more likely when mouse movements are slow.)

- Control will always switch to the left client when moving to the left hand side of the server's left most screen.

- When returning to the server from the left client, control will always be returned to the central screen no matter where it left from.

- Control will sometimes switch to the right client when moving to the right hand side of the server's central screen (it becomes more likely when mouse movements are slow.)

- Control will _never_ switch to the right client when moving to the right hand side of the server's left or right most screens, moreover...

- When moving to the right hand side of the left most server screen, and into the central screen, the synergy logs show pairs of messages indicating that control was passed to the _left_ client (not the right) and then immediately returned to the server.

**Comment by tenleftfingers** [comment]
I have the same issue. If I can provide any logs to help, please let me know.

**Comment by appleshampooid** [comment]
I have the same issue as well, albeit with a simple setup.

**Comment by eudoxos** [comment]
+1 for me, both clients 1.8 (upgraded the other one from 1.6 to make sure), server has 3 screens next to each other, client is laptop with 1 screen. When I move to the client (laptop) left from the main machine, the cursor jumps to the leftmost edge of the laptop screen and cannot leave it (unless controlled from the laptop locally).

**Comment by donengel** [comment]
+1 for me (OS X server, CentOS client)

**Comment by jwestfall69** [comment]
I have this same issue.  My setup is

OS X (client) <=> X Windows 0.0 (server) <=> X Windows 0.1

I did a bit of debugging and was able to resolve the issue for my specific setup.  The problem is that the result from XQueryPointer() is not being taken into account.  It will return false of the mouse pointer isnt on the screen you are asking about, however the x/y mouse data it returns will be for the screen the mouse is on.

In my setup this meant when the mouse was going from X Windows 0.1 -> 0.0, synergys saw the left edge of 0.1 as being the left edge of 0.0 and could make the mouse jump to the OS X client.  There was also other weirdness when going from X WIndows 0.0 -> 0.1 where the mouse would jump back the left edge of 0.0.

The fix for me was to ignore XQueryPointer() when it returned false so synergys was only processing mouse movements on X Windows 0.0.

This change would only work for people using my type of setup.  If for example you had

X Windows 0.0 (server) <=> X Windows 0.1 <=> OS X (client)

It wouldn't work right.

It seems like synergy needs to either be aware of all the X Displays on the computer and how the are oriented to each other, or each X Display needs to be its own synergy client.  I'm not sure the latter is possible because if you move the cursor fast enough you can switch X Displays without synergy noticing, plus weirdness with hiding the cursor.

**Comment by eudoxos** [comment]
I fixed this by compiling 1.9 from source (commit d0ded4e5) on both client and server and it works well again (though running only 1 local X11 server). So I'd suspect the `XQueryPointer()` is a different issue?

**Comment by jwestfall69** [comment]
The XQueryPointer() stuff is related to having multiple monitors that are separate X screens instead of being one large X screen.

**Comment by eudoxos** [comment]
@jwestfall69 sorry, I wrote to a wrong issue, oops. Please disregard the previous comment.

**Comment by jwestfall69** [comment]
I ended up emailing xorg devel after not finding anything googling or reading the docs for X.  They said there is no function in X that will provide details about how multiple X screens are oriented to each other. 

That will make it impossible to automatically figure out what X screen edges are/aren't the edge of the X display.

**Comment by dsprince** [comment]
Then a manual method of configuring it would do until such an API does become available. In the server configuration/screens and links GUI simply present each X screen on each host as a separately draggable item.

Or it could be done semi-automatically. Just configure and start up as now. When the pointer has reached the left of a screen, and synergy is thinking of switching contexts, wait a half second or so (or one mouse motion event) and if it continues moving left don't switch. If the potential switch was cancelled because it continued left onto a different screen, remember that result and cancel the delay there from then on. (Likewise for each direction on each screen that's important to the synergy layout.) There might be the occasional false switch when starting a fresh config if the user just happens to move the mouse right to the edge of one screen and stop, but once it's passed the threshold once it'll be reliable from then on.
This should probably need to be enabled with a multi-X-screen flag for each machine in the config/setup so that it doesn't hassle simpler, single screen situations.

**Comment by appleshampooid** [comment]
FWIW gtk "recently" dropped support for ZaphodHeads, which was the only way I was using multiple X screens these days. It seems like this setup is getting more and more niche :(. I can no longer do it with recent versions of XFCE (due to the gtk support being dropped).

I think you could still make it work with multiple cards one one machine.

**Comment by dsprince** [comment]
For reference - Covid killed this problem for me. I had to take half the kit to work from home, leaving only enough monitors at either end for a single X screen, which I matched up for remote desktop access. So my problems are now VNC-related rather than synergy.
'Fraid I don't have any way to test if this is still an issue these days.
