### ISSUE TITLE
Pressing Win+L locks Windows server while mouse on Mac client

### ISSUE THREAD

**Issue by totolicious** [deskflow/deskflow#6676]
Hi Symless,
I found an annoying behavior related to the WIN + L key combination.

### Operating Systems ###

Server: Windows 10
Client: Mac OS 10.15.4

### Synergy Version ###

Server: Synergy 2.0.12, protocol version 1.6
Client: Synergy 2.0.12, protocol version 1.6

### Steps to Reproduce ###

1. Start with Windows 10 server and Mac OS client.
2. Keyboard and mouse are active on server (Windows 10 machine)
3. Move mouse pointer from server (Windows 10 machine) to client (Mac OS machine).
4. Press WIN + L while active on the client machine.

Expected result:
While active on the client, pressing WIN+L translates to CMD+L (Mac OS)
While active on the client, CMD +  L should be triggered only on the client and the WIN + L combination should not be triggered on the server.

Actual Results:
By pressing WIN+L while active on the client, the server's OS (Windows 10) is now locked, although the WIN + L keys have been pressed while active on the client.
It is inconvenient because on Mac OS, CMD + L focuses the address bar in Google Chrome.
Besides the side effect above, the expected result also happens (the CMD + L key combination is also received on the client)

### Extra Info ###

* What maybe causing it?
While active on the client, WIN + L is captured by the Windows 10 OS before synergy gets a chance to cancel the keypress event for the server's OS?

* Are there any workarounds?
Stop using WIN+L while active on a MacOS client

* What other apps are you running?
Almost nothing. I was able to reproduce the bug on a fresh restart with all applications closed except Google Chrome and Synergy.

* Does it stop you using Synergy entirely?
No, but it's pretty annoying that I have to retrain myself to not use this CMD+L on the Mac client.

* Did restarting Synergy or the computer help?
No. I was able to reproduce the bug on a fresh restart with all applications closed except Google Chrome and Synergy.

* Is there anything else you can think of
No

**Comment by josephbleau** [comment]
I know this is not ideal but if you are like me and are using this at home and do not necessarily need the ability to lock your windows machine you can disable WINKEY + L with the following guide: https://www.howtogeek.com/howto/windows-vista/disableenable-lock-workstation-functionality-windows-l/

Of course I would love to see this supported correctly in Synergy to begin with.

**Comment by spoergsmaal** [comment]
would love to see this as well. it is very inconvenient when i intend to send cmd+L to my Mac machine, and all that happens is that my host Windows machine locks up. for now, i'll use josephbleau's workaround

**Comment by aquacash5** [comment]
@spoergsmaal We understand that this issue is important to our users. This issue is in our backlog. However, it is not in our intimidate roadmap.

As @josephbleau has mentioned, you can disable the Windows locking feature, or another alternative would be to change the shortcut on macOS using the method described here https://apple.stackexchange.com/questions/174977/how-to-create-custom-keyboard-shortcuts/174979#174979 (the menu item is called `Open Location...`)

**Comment by mvelbaum** [comment]
I'm also being hit by this and it is very annoying, I don't find either workaround acceptable.

**Comment by pupeno** [comment]
This is probably my biggest issue at the moment, since I use cmd-L very frequently on Mac, and keep locking my Windows computer.

**Comment by nbolton** [comment]
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Comment by pupeno** [comment]
Yes, this is still an issue, and a really annoying one for me. win-l is what I naturally press to go to the url of chrome, which happens constantly, and that locks my other computer.

**Comment by nbolton** [comment]
Ok, no problem, re-opening.

**Comment by huanga** [comment]
I'm shuffling things around and this is becoming an issue for me as well, hope a solution can be implemented first party.

**Comment by gabeklavans** [comment]
I may be distracting from the main issue, but for me, with a linux device as the server, ALL my modifier+key combos are shared back to the server when I'm on a client. For example, pressing Alt+Space brings up my quick action bar on my windows client and my linux server. Pressing Meta(Win)+Shift+Right moves windows to the right on both my client and my server. I can't find other any docs/issues mentioning this, and it sounds like it's the larger issue that is also causing this Win+L issue to occur.

**Comment by sithlord48** [comment]
This is out of our control as the windows server will eat the key before we get a chance to read it.

**Comment by huanga** [comment]
Can you please confirm "Completed" as in "Can't fix"?
