### ISSUE TITLE
MSB8020: cmake fails to configure for MSVC 17 2022

### ISSUE THREAD

**Issue by src-r-r** [deskflow/deskflow#7280]
### Operating Systems ###

Server: Windows 11
Client: Irrelevant / Windows 11

### Synergy Version ###

Irrelevant, but using the synergy-core master branch

### Steps to Reproduce ###

Follow [the compile instructions for windows](https://github.com/symless/synergy-core/wiki/Compiling#windows).

One thing to note is that for **Step 2: Install [Visual Studio Community 2019 with Updates](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16)** gets kind of tricky. If you open the installer, you can only download MSVC 2022.

### Log URLs ###

[cmake-error-1.txt](https://github.com/symless/synergy-core/files/12449653/cmake-error-1.txt)

### Extra Info ###

Here's the Cmake command I'm using in Qt Creator:

```
-G Visual Studio 17 2022
-DCMAKE_BUILD_TYPE:STRING=Debug
-DCMAKE_PROJECT_INCLUDE_BEFORE:PATH=%{IDE:ResourcePath}/package-manager/auto-setup.cmake
-DQT_QMAKE_EXECUTABLE:STRING=%{Qt:qmakeExecutable}
-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}
-DCMAKE_C_COMPILER:STRING=%{Compiler:Executable:C}
-DCMAKE_CXX_COMPILER:STRING=%{Compiler:Executable:Cxx}
-DLIB_EAY_DEBUG:FILEPATH=C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib
-DSSL_EAY_DEBUG:FILEPATH=C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib
-DSSL_EAY_DEBUG:FILEPATH=C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib
```

I'm able to successfully compile Synergy using `-G Ninja`, but the problem here is that I can't do any debugging. I also tried using the CLI installation method and get the same error.

And, yes, I've checked multiple times that I have everything v143 C++ related installed.

Is it because MSVC installs in `Program Files` instead of `Program Files (x86)` like MSVC 2019 did?

Help is appreciated. Thank you.

**Comment by nbolton** [comment]
Thanks for reporting this, could you try the latest `master` to see if this is still an issue?
