### ISSUE TITLE
The mouse cannot be moved from the main display

### ISSUE THREAD

**Issue by githublaohu** [deskflow/deskflow#7305]
Server: ubuntu 22.04 , synergy:  v3.0.77.2-rc3
Client: windows 11, synergy:  v3.0.73.7-rc3

The server has three monitors, with the main monitor in the middle. The mouse cannot be moved from the main display to the client. The mouse can only be moved from the left monitor to the client

**Comment by nbolton** [comment]
Hi, sorry for the late reply. As a customer you are able to [open a support ticket](https://symless.com/synergy/contact). Did you happen to do this yet?
