### ISSUE TITLE
Build error ld: Undefined symbols:

### ISSUE THREAD

**Issue by Rafinol** [deskflow/deskflow#7311]
Operating Systems: Sonoma 14.1.2

Qt 5.12.12

Synergy version: 1.13.1

Error when I try build:

ld: Undefined symbols:
  _CRYPTO_free, referenced from:
      SecureSocket::showCertificate() in libnet.a[5](SecureSocket.cpp.o)
  _ERR_error_string_n, referenced from:
      SecureSocket::showError(char const*) in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::getError() in libnet.a[5](SecureSocket.cpp.o)
  _ERR_get_error, referenced from:
      SecureSocket::showError(char const*) in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::getError() in libnet.a[5](SecureSocket.cpp.o)
  _ERR_peek_error, referenced from:
      SecureSocket::checkResult(int, int&) in libnet.a[5](SecureSocket.cpp.o)
  _EVP_sha256, referenced from:
      SecureSocket::verifyCertFingerprint() in libnet.a[5](SecureSocket.cpp.o)
  _OPENSSL_init_crypto, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _OPENSSL_init_ssl, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _OPENSSL_sk_num, referenced from:
      showCipherStackDesc(stack_st_SSL_CIPHER*) in libnet.a[5](SecureSocket.cpp.o)
      showCipherStackDesc(stack_st_SSL_CIPHER*) in libnet.a[5](SecureSocket.cpp.o)
  _OPENSSL_sk_value, referenced from:
      showCipherStackDesc(stack_st_SSL_CIPHER*) in libnet.a[5](SecureSocket.cpp.o)
  _OpenSSL_version, referenced from:
      SecureSocket::showSecureLibInfo() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::showSecureLibInfo() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::showSecureLibInfo() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::showSecureLibInfo() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::showSecureLibInfo() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CIPHER_description, referenced from:
      SecureSocket::showSecureConnectInfo() in libnet.a[5](SecureSocket.cpp.o)
      showCipherStackDesc(stack_st_SSL_CIPHER*) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_check_private_key, referenced from:
      SecureSocket::loadCertificates(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_free, referenced from:
      SecureSocket::~SecureSocket() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_new, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_set_options, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_use_PrivateKey_file, referenced from:
      SecureSocket::loadCertificates(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_CTX_use_certificate_file, referenced from:
      SecureSocket::loadCertificates(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_accept, referenced from:
      SecureSocket::secureAccept(int) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_connect, referenced from:
      SecureSocket::secureConnect(int) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_free, referenced from:
      SecureSocket::~SecureSocket() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_get1_peer_certificate, referenced from:
      SecureSocket::verifyCertFingerprint() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::showCertificate() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_get_ciphers, referenced from:
      SecureSocket::showSecureCipherInfo() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_get_client_ciphers, referenced from:
      SecureSocket::showSecureCipherInfo() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_get_current_cipher, referenced from:
      SecureSocket::showSecureConnectInfo() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_get_error, referenced from:
      SecureSocket::checkResult(int, int&) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_new, referenced from:
      SecureSocket::createSSL() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::secureAccept(int) in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::secureConnect(int) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_read, referenced from:
      SecureSocket::doRead() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::doRead() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::secureRead(void*, int, int&) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_set_fd, referenced from:
      SecureSocket::secureAccept(int) in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::secureConnect(int) in libnet.a[5](SecureSocket.cpp.o)
  _SSL_shutdown, referenced from:
      SecureSocket::~SecureSocket() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::close() in libnet.a[5](SecureSocket.cpp.o)
      non-virtual thunk to SecureSocket::close() in libnet.a[5](SecureSocket.cpp.o)
  _SSL_write, referenced from:
      SecureSocket::doWrite() in libnet.a[5](SecureSocket.cpp.o)
      SecureSocket::secureWrite(void const*, int, int&) in libnet.a[5](SecureSocket.cpp.o)
  _TLS_client_method, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _TLS_server_method, referenced from:
      SecureSocket::initContext(bool) in libnet.a[5](SecureSocket.cpp.o)
  _X509_NAME_oneline, referenced from:
      SecureSocket::showCertificate() in libnet.a[5](SecureSocket.cpp.o)
  _X509_digest, referenced from:
      SecureSocket::verifyCertFingerprint() in libnet.a[5](SecureSocket.cpp.o)
  _X509_free, referenced from:
      SecureSocket::showCertificate() in libnet.a[5](SecureSocket.cpp.o)
  _X509_get_subject_name, referenced from:
      SecureSocket::showCertificate() in libnet.a[5](SecureSocket.cpp.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/synergyc] Error 1
make[1]: *** [src/cmd/synergyc/CMakeFiles/synergyc.dir/all] Error 2
make: *** [all] Error 2
18:22:07: The process "/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake" exited with code 2.
Error while building/deploying project synergy-core (kit: Desktop Qt 5.12.12 clang 64bit)
When executing step "Build"

**Comment by nbolton** [comment]
Hello, sorry for the late reply. Could you try the latest `master` and see if this issue persists? I believe it should be fixed.
