### ISSUE TITLE
WiX error: System cannot find the file

### ISSUE THREAD

**Issue by OddinD** [deskflow/deskflow#7339]
Hi, i have a pb when i dl synergy i don t have the fil openssl and so i arrived at the app creation the cmd say me the systme dont find the file 
![Capture](https://github.com/symless/synergy-core/assets/162481041/799160c7-e420-44e7-8c77-7b258f2d3c34)
 thank you for your help

**Comment by nbolton** [comment]
What happens when you run `python ./scripts/install_deps.py`?

**Comment by nbolton** [comment]
Hello, could you try again with latest `master`? I have changed the way we resolve the OpenSSL dependency on Windows.

**Comment by sithlord48** [comment]
this is fixed on current `master`
