### ISSUE TITLE
Unable to install deps on Ubuntu 20: `File "setup.py" not found`

### ISSUE THREAD

**Issue by SummrWhit** [deskflow/deskflow#7418]
### Discussion

- [X] Yes, and I still want to report a bug

### What type of Synergy user are you?

Community user

### Product name

Synergy 3

### Synergy version number

before use

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux or Unix
- [ ] Other

### OS versions or Linux distros

ubunutu2004

### Synergy configuration

Lunux

### What steps will reproduce the problem?

compile

### Log output

```shell
python scripts/install_deps.py
Using virtual environment for: /home/xxx/Project/synergy-core/scripts/install_deps.py
Installing required modules...
Running: /home/xxx/Project/synergy-core/build/python/bin/python -m pip install -e scripts
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/xxx/Project/synergy-core/scripts
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by nbolton** [comment]
Thanks for the bug report. Ubuntu 20 has an old version of Python which doesn't seem to support `pyproject.toml` in the same way as the Python version on Ubuntu 22 and 24. Are you planning to stay on Ubuntu 20 for a while?

**Comment by nbolton** [comment]
Just a thought, try: `pip install --upgrade pip`

**Comment by nbolton** [comment]
@SummrWhit Hi, do you have any plans do upgrade to Ubuntu 22?

**Comment by SummrWhit** [comment]
no,not in a short time在 2024年8月20日，06:06，Nick Bolton ***@***.***> 写道：﻿
@SummrWhit Hi, do you have any plans do upgrade to Ubuntu 22?

**Comment by sithlord48** [comment]
Closing since the file does not exist any longer
