### ISSUE TITLE
Unable to compile on Windows 7 against Qt 5

### ISSUE THREAD

**Issue by AnrDaemon** [deskflow/deskflow#7490]
### What type of Synergy user are you?

Community user

### Discussion

- [X] I want to report a bug (I don't want to start a discussion)

### Product name

Synergy 1

### Synergy version number

1.15

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux or Unix
- [ ] Other

### OS versions or Linux distros

Windows 7 Pro SP1

### Synergy configuration

Synergy-Core

### What steps will reproduce the problem?

Open repo, pull 1.15 release tag, run buildscript.

### Log output

```shell
-- Selecting Windows SDK version 8.1 to target Windows 6.1.7601.
-- Enabling warnings as errors (MSVC)
-- Version number (semver): 1.15.0
-- Version number for (Microsoft 4-part): 1.15.0.0
-- Version number for (Microsoft CSV): 1,15,0,0
-- Product name: Synergy 1 Community Edition
-- Enabling dev thanks message
-- Disabling debug build
-- Found OpenSSL binaries at: C:\Cygwin64\bin\openssl.exe
-- Configuring incomplete, errors occurred!
See also "C:/Users/anrdaemon/Documents/synergy-core/build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine версии 16.9.0+5e4b48a27 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

CMake Error at cmake/Libraries.cmake:289 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/Libraries.cmake:10 (config_qt)
  CMakeLists.txt:28 (configure_libs)

```
```


### Additional information

I'm unable to compile 1.15. It requires Qt6, which requires updating Qt manager, which only works on W10. My building clients are W7 right now.

**Comment by AnrDaemon** [comment]
Qt maintenance tool errors out after upgrade

```
---------------------------
MaintenanceTool.exe - Точка входа не найдена
---------------------------
Точка входа в процедуру GetPointerFrameTouchInfoHistory не найдена в библиотеке DLL USER32.dll. 
---------------------------
ОК   
---------------------------
```

**Comment by nbolton** [comment]
Thanks, are you planning on sticking with Windows 7 and Qt 5 for a while? Qt 6 was released in 2020, so it's fairly mature. I see that [Qt 6 OS support](https://doc.qt.io/qt-6/supported-platforms.html) does not include Windows 7, so I suppose it depends on how long you're sticking with Windows 7.

**Comment by AnrDaemon** [comment]
Some of my client systems are W7 still, and I'd like to ensure interoperability. Synergy is an unique offer on the market, unlike many other RDesktop solutions.

**Comment by nbolton** [comment]
> Some of my client systems are W7 still, and I'd like to ensure interoperability. Synergy is an unique offer on the market, unlike many other RDesktop solutions.

Good to know, I'll think about reintroducing Qt 5, but we had planned to leave it behind for simiplicity.

**Comment by nbolton** [comment]
To clarify, we have decided not to support Qt5. If you want Qt5 support, perhaps you could use an old version of Synergy or use Input Leap (who seem to want to support Qt5).

**Comment by AnrDaemon** [comment]
Thanks for the info. I'll see, what I can do.
