### ISSUE TITLE
FATAL: core server binary does not exist

### ISSUE THREAD

**Issue by jiapei100** [deskflow/deskflow#7514]
### What type of Synergy user are you?

Customer

### Support ticket number (for customers)

# 183795

### Discussion

- [X] I want to report a bug (I don't want to start a discussion)

### Product name

Synergy 1

### Synergy version number

1.16.0-beta

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux or Unix
- [ ] Other

### OS versions or Linux distros

- Ubuntu 24.04

### Synergy configuration

- Windows 11 left, Ubuntu 24.04 right

### What steps will reproduce the problem?

Just typed `./synergy` under Ubuntu 24.04, and obtained:

```zsh
➜  ~ [2024-09-15T22:33:40] INFO: Synergy v1.16.1-beta
[2024-09-15T22:33:40] INFO: no .env file in dir: /home/lvision
[2024-09-15T22:33:40] INFO: no .env file in app config dir: ~/.config/Synergy
[2024-09-15T22:33:40] INFO: starting core server process (desktop mode)
[2024-09-15T22:33:40] FATAL: core server binary does not exist
```

![Screenshot from 2024-09-15 22-33-55](https://github.com/user-attachments/assets/25fa3e65-a316-4742-94fa-601cff81a074)

**Comment by nbolton** [comment]
Ah, please ignore the "please raise a ticket" message. It got confused because there is a `#` in front of the ticket number.

**Comment by nbolton** [comment]
@jiapei100 Hey, did you build this yourself? I think that it might have something to do with the current working directory.

**Comment by nbolton** [comment]
@jiapei100 Would you mind elaborating on why you closed your issue? I think it might benefit others.

**Comment by jiapei100** [comment]
@nbolton 
Hi, I just open up another issue: https://github.com/deskflow/deskflow/issues/7531
