### ISSUE TITLE
Holding a key and exiting screen of Linux Wayland KDE client gets key stuck

### ISSUE THREAD

**Issue by enzious** [deskflow/deskflow#7518]
### What type of Synergy user are you?

Customer

### Discussion

- [X] I want to report a bug (I don't want to start a discussion)

### Product name

Synergy 1

### Synergy version number

1.16.0 beta

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux or Unix
- [ ] Other

### OS versions or Linux distros

- (Windows/Linux) (server)
- Gentoo Linux KDE Plasma 6 (client)

### Synergy configuration

- (windows/linux) (server)
- Gentoo Linux KDE Plasma 6 (client)

### What steps will reproduce the problem?

1. Start client and server
2. Move mouse to client screen
3. Hold key
4. Leave client screen

### Log output

```shell
[2024-09-16T13:37:51] ERROR: ei: 🪲  Bug: ei_device_keyboard_key: device is not emulating
```

**Comment by enzious** [comment]
Not convinced it's just a KDE bug. Looking into the code a bit.

**Comment by enzious** [comment]
- Updating to libei 1.3.0 did not resolve the issue.
- Commenting out the calls to `ei_device_stop_emulating(...)` mitigated the issue but resulted in 'share' dialog on re-entry.
- Commenting out code causing 'device is not emulating' log did not resolve the issue.

**Comment by enzious** [comment]
I was right, here is what fixed it for me: https://github.com/enzious/deskflow/tree/fix/stuck-keys-on-leave

**Comment by sithlord48** [comment]
Tested your fix in input-leap it works perfect please make a pr here for this !

**Comment by enzious** [comment]
> Tested your fix in input-leap it works perfect please make a pr here for this !

That change may break edge cases. I'll submit a PR later that handles the issue better.

**Comment by sithlord48** [comment]
I will update to be in sync with you changes. For both here and there.

**Comment by nbolton** [comment]
Thanks for the bug report and PRs.
