### ISSUE TITLE
Compatibility between Input Leap and Synergy

### ISSUE THREAD

**Issue by sithlord48** [deskflow/deskflow#7526]
We would like to be compatible with  synergy , barrier and input-leap 

The protocol is identical other then the "Hello" and "Helloback" Messages
   - Synergy / Deskflow use `Synergy`
   - Barrier / Input-leap user `Barrier` 

I propose the follow solution:

-  Client 
   - Accept the initial hello (log if barrier or synergy)
   - Reply with the matching hello back

- Server
   - Default to barrier 
   - Allow user to change this in server settings

**Comment by nbolton** [comment]
I believe that a setting under _Edit -> Preferences -> Advanced_ would be useful.

**Comment by sithlord48** [comment]
we can check for both when checking the hello message but , what do we send as an inital i think that should be barrier with an option for "legacy" that uses synergy ?

**Comment by nbolton** [comment]
How about we have a setup step in the GUI (on first open, after the name screen) called "Protocol compatibility" with 2 radio buttons:

```
( o )  Deskflow (Synergy protocol)
(   )  Input Leap (Barrier protocol)
```

Then we change this:
```
// Keep the "Synergy" name for hello to preserve compatibility with Synergy
const char *const kMsgHello = "Synergy%2i%2i";
const char *const kMsgHelloBack = "Synergy%2i%2i%s";
```

To something like this but better:
```
// Default to "Synergy" for backward compatibility with Synergy
std::string msgHello = "Synergy%2i%2i";
std::string msgHelloBack = "Synergy%2i%2i%s";

void setProtocol(const std::string &name) {
  msgHello = name + "%2i%2i";
  msgHelloBack = name + "%2i%2i%s";
}
```

It's probably important that we keep the `Synergy` protocol as default since it's the most common and also sort of an industry standard (for example, Wireshark identifies the protocol as Synergy). We probably do not want to change the protocol by default, as it breaks backward compatibility.

![image](https://github.com/user-attachments/assets/6c04351d-a7d7-478e-ad41-c25df0533736)

**Comment by sithlord48** [comment]
can you check with input-leap also please

**Comment by sithlord48** [comment]
If you have an setup that is 

Synergy (client) | deskflow (server) | barrier(client) 

The server needs to know that when "synergy" connects to use its  hand shake and when barrier connect to use the barrier one.. I think this has to be a setting the server can change per client. 

Do we want to support the case of an input-leap server with synergy client we may need to also allow the client to as a connect to server option.

**Comment by nbolton** [comment]
Aha, so you want to support a mix of Barrier and Synergy. In that case we can make the protocol setting per client (so the client says whether it's Synergy/Barrier), and also on the server check against both Synergy/Barrier hello messages when a client connects (and accept either).

**Comment by nbolton** [comment]
@sithlord48 As discussed, I'll have a shot at this and use your work so far (d43b113a7149eab3fd95991a3a030b8e731e365e) as a starting point.
