### ISSUE TITLE
FATAL: core server binary does not exist

### ISSUE THREAD

**Issue by jiapei100** [deskflow/deskflow#7531]
### Project

Deskflow

### Deskflow version number

1.17.0

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

- Ubuntu 24.04

### Deskflow configuration

- Build from source

### What steps will reproduce the problem?

Just **Start Deskflow**

And I got this dialog:
![deskflow_error](https://github.com/user-attachments/assets/3056aedd-6b4c-4c69-afa3-af19cd875cbe)

on my terminal, I got:
```zsh
➜  ~ deskflow                               
[2024-09-19T11:10:24] INFO: Deskflow v1.17.0
[2024-09-19T11:10:24] INFO: no .env file in dir: ~
[2024-09-19T11:10:24] INFO: no .env file in app config dir: ~/.config/Deskflow
[2024-09-19T11:10:24] INFO: starting core server process (desktop mode)
[2024-09-19T11:10:24] FATAL: core server binary does not exist
[2]    1038620 IOT instruction (core dumped)  deskflow
```

**Comment by jiapei100** [comment]
@nbolton 
I just used traditional **CMake** build out-of-source.

And, I also tried **meson** just now. With **meson**, I cannot even generate the binary to run...

**Comment by nbolton** [comment]
Yeah, we use meson in a weird way (the way I did it was a bad idea) and are planning to remove it: https://github.com/deskflow/deskflow/discussions/7546

**Comment by nbolton** [comment]
> try running it from the project root instead of `cd` into the bin dir

@jiapei100 Did you try this?

**Comment by jiapei100** [comment]
@nbolton 
yeah, tried already.

So, are you recommending go with **cmake** rather than **meson**??

**Comment by nbolton** [comment]
> **cmake** rather than **meson**

Yes, use cmake. We only use meson (badly) to satisfy some deps, but that's going away soon.

**Comment by sithlord48** [comment]
duplicate #7937
