### ISSUE TITLE
`error: macro "__DATE__" might prevent reproducible builds`

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7545]
### Project

Deskflow

### Deskflow version number

1.17.0

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Debian

### Deskflow configuration

n/a

### What steps will reproduce the problem?

1. Build on Debian stable

### Log output

```shell
In file included from /build/deskflow-1.16.1~beta+r1/src/lib/synergy/App.cpp:30:
/build/deskflow-1.16.1~beta+r1/src/./lib/common/copyright.h:32:28: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
   32 |   const std::string date = __DATE__;
      |                            ^~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [src/lib/synergy/CMakeFiles/synlib.dir/build.make:79: src/lib/synergy/CMakeFiles/synlib.dir/App.cpp.o] Error 1
```

### Additional information

Reported by WrathOfAchilles on IRC

**Comment by nbolton** [comment]
The solution could be either:
1. Make `-Werror` optional (so package maintainers don't need to patch it out)
2. Add a `#pramga` ignore warning on the offending line of code (if possible)

**Comment by sithlord48** [comment]
This feature should go.. we can not make a reproducible build if the contents of the file change based only on when it was built.
