### ISSUE TITLE
Move Linux commands from `config.yaml` to `install_deps.sh`

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7589]
As discussed in https://github.com/deskflow/deskflow/discussions/7588, because running Python is a PITA for some people on some Linux/Unix-like distros, I think the best thing to do is move the commands from `config.yml` into `install_deps.sh` and make the Python deps script (`install_deps.py`) macOS and Windows only.

Related: #7446, #7587

**Comment by fosterlynch** [comment]
I followed the installation instructions, (as of version 1.17.0)

after not having much luck with ```scripts/install_deps.py``` (ubuntu 20.04, no extra monitor)

I tried the following

> You can either copy/paste the commands for your OS from [config.yaml](https://github.com/deskflow/deskflow/blob/master/config.yaml) or use the deps script.



so i figured I'd try to run the linux install commands directly 

running 
```
sudo apt-get install -y \
>           cmake \
>           make \
>           ninja-build \
>           g++ \
>           file \
>           xorg-dev \
>           libx11-dev \
>           libxtst-dev \
>           libssl-dev \
>           libglib2.0-dev \
>           libgdk-pixbuf-2.0-dev \
>           libnotify-dev \
>           libxkbfile-dev \
>           qt6-base-dev \
>           qt6-tools-dev \
>           libgtk-3-dev \
>           libgtest-dev \
>           libgmock-dev \
>           libpugixml-dev \
>           libei-dev \
>           libportal-dev \
>           libtomlplusplus-dev \
>           libcli11-dev
```
results in 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgdk-pixbuf-2.0-dev
E: Couldn't find any package by glob 'libgdk-pixbuf-2.0-dev'
E: Couldn't find any package by regex 'libgdk-pixbuf-2.0-dev'
E: Unable to locate package qt6-base-dev
E: Unable to locate package qt6-tools-dev
E: Unable to locate package libei-dev
E: Unable to locate package libportal-dev
E: Unable to locate package libtomlplusplus-dev
E: Unable to locate package libcli11-dev
```

happy to create an issue ticket if needed

**Comment by nbolton** [comment]
> E: Unable to locate package qt6-base-dev
> E: Unable to locate package qt6-tools-dev

Damn, I guess no Qt6 on Ubuntu 20 :disappointed: 
https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=qt6

Could you remind me again why you don't want to upgrade to Ubuntu 22? I'm considering re-introducing Qt5 support, which would be a bit of a pain, as it's seriously old now.

**Comment by sithlord48** [comment]
We don't need Qt5 support those ppl can use input-leap or barrier ...

**Comment by fosterlynch** [comment]
@nbolton any thoughts on using a docker container? wondering if that helps circumnavigate the base os issues? not sure if that opens a can of worms, just curious!

**Comment by fosterlynch** [comment]
fwiw, regarding the other installs not being found, i pulled `1.15.0-snapshot+r3`

looked up libgdk-pixbuf-2.0-dev here https://packages.ubuntu.com/search?keywords=pixbuf&searchon=names&suite=focal&section=all

and it looks like ti should be `libgdk-pixbuf2.0-dev` not `libgdk-pixbuf-2.0-dev`

I changed that in the config.yaml and the installs then run correctly. (though i don't know if theres a ciritical difference between pixbuf-2.0 and pixbuf2.0 ...)

**Comment by nbolton** [comment]
> @nbolton any thoughts on using a docker container? wondering if that helps circumnavigate the base os issues? not sure if that opens a can of worms, just curious!

I'm not sure what you mean. We use Docker containers to build, but we don't test against Ubuntu 20.

> and it looks like ti should be `libgdk-pixbuf2.0-dev` not `libgdk-pixbuf-2.0-dev`
> I changed that in the config.yaml and the installs then run correctly. (though i don't know if theres a ciritical difference between pixbuf-2.0 and pixbuf2.0 ...)

Oh that's quite interesting, did they rename it between 20 and 22?

**Comment by fosterlynch** [comment]
> Oh that's quite interesting, did they rename it between 20 and 22?

that appears to be the case 

https://packages.ubuntu.com/search?keywords=libgdk-pixbuf-2.0-dev&searchon=names&suite=jammy&section=all

**Comment by fosterlynch** [comment]
> Could you remind me again why you don't want to upgrade to Ubuntu 22? I know it's not EOL until next year, so I'm considering re-introducing Qt5 support, which would be a bit of a pain, as it's seriously old now.

Work laptop, no control over when i can upgrade ubuntu version

**Comment by sithlord48** [comment]
The easiest thing for you todo is going to be installing Qt6 on your machine. You might be able to find a PPA that provides it or use the Qt online installer to install it then build.

**Comment by fosterlynch** [comment]
didn't consider that, thank you @sithlord48! I will give that a go and report back if that helps ubuntu 20 machines!

**Comment by purva1903** [comment]
Trying to solve issue #7589
An issue was identified with the execution of certain Linux commands, which was affecting the system's ability to perform [insert specific task/process].The problem was traced to incorrect command syntax and environment variable misconfigurations.
To move Linux commands from config.yaml to install_deps.sh for macOS and Windows only:

1. Modify install_deps.sh to detect the OS and run platform-specific commands (macOS: brew, Windows: pacman or other tools).
2. Skip Linux commands in the script by checking the OS.
3. Update config.yaml to reference install_deps.sh for macOS/Windows, and either remove or keep Linux-specific commands if necessary.
4. Test the script on macOS and Windows to ensure proper functionality across platforms.

**Comment by nbolton** [comment]
> To move Linux commands from config.yaml to install_deps.sh for macOS and Windows only:

Sorry but I'm struggling to make sense of this.

The issue is related to Linux, not Windows and macOS.

**Comment by nbolton** [comment]
My original feature request is now obsolete since we're deprecating the scripts.

**Comment by fosterlynch** [comment]
@nbolton I am coming back to this discussion, I see there are some new statements. Are we still interested in trying to make deskflowy compatible with ubuntu20.04? I know the userbase is probably not the majority, but I am still happy to try to get QT5 installed on ubuntu20.04 and then see what else deskflowy needs to properly install.

**Comment by nbolton** [comment]
> Are we still interested in trying to make deskflowy compatible with ubuntu20.04

Unfortunately not. The Deskflow development philosophy is leading edge. If you need legacy OS support, please use Synergy or Input Leap.

From the readme:
> Leading edge releases (we don't focus on supporting older systems)
