### ISSUE TITLE
Submit Flatpak package to Flathub

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7593]
### Project

Deskflow

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Any

### Deskflow configuration

n/a

### What problem are you trying to solve?

We used to build our own Flatpak when we used Azure Pipelines, but we didn't add it new GitHub CI workflow.

### What solution do you propose?

Submit a Flatpak package to Flathub as part of the new CI workflow.

**Comment by adrianinsaval** [comment]
I would advise to submit the package to flathub rather than releasing on your own

**Comment by sithlord48** [comment]
We also need to have as a prereq for all of our installers a  proper 
`install` target , we have this mostly correct for linux only but we lack metadata that flatpaks require such as appsteam data

**Comment by nbolton** [comment]
Does it make sense to say this?
> Submit a Flatpak package to Flathub as part of the new CI workflow.

I'm new to Flathub.

**Comment by adrianinsaval** [comment]
Maybe, for stable releases you can automate creating a PR in the flathub repo for it I think. But ultimately to publish a package on flathub you need to merge a PR in the repo for your package. For CI running on every commit publishing on your own probably makes more sense

**Comment by sithlord48** [comment]
> Maybe, for stable releases you can automate creating a PR in the flathub repo for it I think. But ultimately to publish a package on flathub you need to merge a PR in the repo for your package. For CI running on every commit publishing on your own probably makes more sense

Once on flathub they have a bot that will look when you tags are updated and it will suggest the changes needed for a new release.

**Comment by sithlord48** [comment]
https://github.com/flathub/flathub/pull/5855 <- mostly waiting for 1.17.2 release as we can not build "master" on flathub only releases.

**Comment by sithlord48** [comment]
Done
