### ISSUE TITLE
Clipboard sharing not working on Wayland

### ISSUE THREAD

**Issue by rayrayrayraydog** [deskflow/deskflow#7600]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Local developer build (built it yourself)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Server: Fedora 40 UBlue - bazzite (Wayland)
Client: macOS 15.0

### Deskflow configuration

- bazzite Server on the left (Wayland + KDE Plasma 6.1.5), macOS 15.0 client on the right.  Used the GUI with defaults including encryption

### What steps will reproduce the problem?

Start deskflow with above configuration and connect the macOS client.  I cannot share any clipboard contents between the two computers.  It doesn't seem to matter if I copy from the server or the client.  The logs on both computers indicate that the clipboard is updated but I can still only paste from each machine's local clipboard contents.

### Log output

```shell
** From the server ** 

[2024-10-01T19:19:11] INFO: screen "raymac" grabbed clipboard 1 from "raymac"
[2024-10-01T19:19:14] INFO: switch from "raymac" to "k6" at 2185,824
[2024-10-01T19:19:14] INFO: entering screen
[2024-10-01T19:19:14] INFO: screen "raymac" updated clipboard 0
[2024-10-01T19:19:14] INFO: screen "raymac" updated clipboard 1
[2024-10-01T19:21:26] INFO: switch from "k6" to "raymac" at 110,448
[2024-10-01T19:21:26] INFO: leaving screen
[2024-10-01T19:21:33] INFO: switch from "raymac" to "k6" at 2164,390
[2024-10-01T19:21:33] INFO: entering screen
[2024-10-01T19:23:26] INFO: switch from "k6" to "raymac" at 84,26
[2024-10-01T19:23:26] INFO: leaving screen
[2024-10-01T19:23:30] INFO: switch from "raymac" to "k6" at 2187,695
[2024-10-01T19:23:30] INFO: entering screen
```

**Comment by sithlord48** [comment]
From my understanding this is an xdg-desktop-portal implimention problem not a direct deskflow issue.

**Comment by nbolton** [comment]
I made the title a bit more general as clipboard support for both client and server still needs to be implemented for non-X.

**Comment by nbolton** [comment]
> I just want to give the team a **huge thanks** for the Wayland support!! This is huge! I will be here to help test as the project gets updated as a daily user of the app, coming from synergy-core.

Thanks should go to @whot, @ofourdan, and @p12tic :slightly_smiling_face:

**Comment by sithlord48** [comment]
Testing needs to happen to test clipboard in the following configurations

- [ ] Windows <-> Windows 
- [ ] Windows <-> MacOS
- [ ] Windows <-> X11
- [ ] MacOS <-> MacOS
- [ ] MacOS <-> Windows
- [ ] MacOS <-> X11
- [ ] X11<-> X11
- [ ] X11 <-> MacOS
- [ ] X11 <-> Windows 

We don't have to test wayland until https://github.com/flatpak/xdg-desktop-portal/issues/1434 is resolved

**Comment by nbolton** [comment]
I belive this is Wayland specific and have updated the title.

**Comment by sithlord48** [comment]
If its wayland only im gonna close as not our bug
