### ISSUE TITLE
Error when trying to run server on Arch Linux CachyOS using Hyprland with Wayland

### ISSUE THREAD

**Issue by EthanDarling8** [deskflow/deskflow#7613]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Local developer build (built it yourself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Arch Linux CachyOS latest release using Hyprland

### Deskflow configuration

- Arch linux server on the left
- Windows 11 client on the right

### What steps will reproduce the problem?

1. Start server
2. See the following in the logs:
`failed to initialize input capture session, quitting: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.InputCapture” on object at path /org/freedesktop/portal/desktop`

### Log output

```shell
[2024-10-03T09:41:10] NOTE: started server, waiting for clients
[2024-10-03T09:41:10] WARNING: current primary screen is not entered on shutdown
[2024-10-03T09:41:10] NOTE: stopped server
[2024-10-03T09:41:11] INFO: using ei screen for wayland
[2024-10-03T09:41:11] ERROR: failed to initialize input capture session, quitting: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.InputCapture” on object at path /org/freedesktop/portal/desktop
```

### Additional information

Here is a similar issue that was closed for a different linux version: https://github.com/deskflow/deskflow/issues/7494

**Comment by EthanDarling8** [comment]
After looking around, the Input Capture Desktop Portal might be something that needs to be implemented into Hyprland? https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/268 Have we seen any users who have had success using Deskflow with Hyprland?

**Comment by sithlord48** [comment]
Please see this discussion https://github.com/deskflow/deskflow/discussions/7499  I have created issues for all the portals you can see any response and or track other wayland related issues here in this discussion

**Comment by EthanDarling8** [comment]
Closed this issue as it is already discussed in https://github.com/deskflow/deskflow/discussions/7499

**Comment by nbolton** [comment]
Looking forward to better Hyprland support! :rocket:
