### ISSUE TITLE
Cannot use comma in config file

### ISSUE THREAD

**Issue by Azzurite** [deskflow/deskflow#7617]
### Project

Deskflow

### Deskflow version number

v1.17.0+r1 (44bd69fd)

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Windows 10

### Deskflow configuration

Hotkey which includes the `,` key

### What steps will reproduce the problem?

Create a hotkey which includes the `,` key

### Log output

```shell
[2024-10-05T11:20:05] ERROR: cannot read configuration "***/AppData/Local/Deskflow/deskflow-server.conf": read error: line 40: missing )
```

**Comment by nbolton** [comment]
Related: #7130
