### ISSUE TITLE
Drop a warning indicator in the GUI for end users for awareness for the known issues or workarounds

### ISSUE THREAD

**Issue by Dentrax** [deskflow/deskflow#7620]
### Project

Deskflow

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

- macOS 14

### Deskflow configuration

- Default

### What problem are you trying to solve?

There is some known-issues or [workarounds](https://github.com/deskflow/deskflow/wiki/Workarounds) in the Wiki. We should make this more visible for the end-user in automated manner.

### What solution do you propose?

In GUI, pop-up a new Warning indicator (or another performance tuning page) if some conditions are matched with given known-issues. For example:
* If I'm on the MacOS and `awdl0` is `up`, and macOS version does match with the predefined range, show an indicator to tell "Consider disable this or use network cable to gain performance boost"
* If German keyboard layout is detected, say to user "Consider pass `setxkbmap de` in your `. xinitrc` file".
* And cases like this...

**Comment by sithlord48** [comment]
This is a rabbit hole of pointless (for our app) checks. Users should read the documentation if they have issues. Our job is to make the documents easy to find and easy to understand.

**Comment by nbolton** [comment]
I agree with @sithlord48 and think people are likely to ignore the tip/warning initially (it would be white noise) then search for docs anyway (using a search engine, etc). It's our job (short term) to make our docs discoverable by search engines, and of course long term to fix the bugs that make the workarounds necessary.
