### ISSUE TITLE
macOS arm64 GitHub build is "damaged" and cannot be opened

### ISSUE THREAD

**Issue by spnda** [deskflow/deskflow#7623]
### Project

Deskflow

### Deskflow version number

1.17

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

macOS 15.0.1 (24A348)

### Deskflow configuration

macOS 15 Client/Server (not yet configured)

### What steps will reproduce the problem?

1. Download Deskflow from the GitHub release page
2. Try and open it through Launchpad
3. Receive following message
> “Deskflow” is damaged and can’t be opened. You should move it to the Trash.

### Additional information

I tried looking through `Console` but couldn't find anything. I'd be happy to provide some logs, though I simply don't know where they are and don't have time looking for them right now. I would try digging deeper tomorrow, I found this issue right before heading to bed.
The downloaded app bundle is 66.2MB in size.

**Comment by sithlord48** [comment]
This can be "fixed" by running xattr -c on the Offending .app file . Its due to lack of signing.

**Comment by nbolton** [comment]
I think we can fix this by signing the bundle but we should decide if we should have brew as the official distribution channel which solves this problem by self signing.

Check out the wiki page for the full instructions: https://github.com/deskflow/deskflow/wiki/Running-on-macOS

**Comment by sithlord48** [comment]
I used not our bub only because  it's not always upstream sometimes it's
just the platform

**Comment by spnda** [comment]
> This can be "fixed" by running xattr -c on the Offending .app file . Its due to lack of signing.

Ah, yes, this does indeed let me open the application as expected.

**Comment by sithlord48** [comment]
Duplicate Issue https://github.com/deskflow/deskflow/issues/7606
