### ISSUE TITLE
need binary for macOS of intel CPU

### ISSUE THREAD

**Issue by mmsim6** [deskflow/deskflow#7625]
### Project

Deskflow

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

macos

### Deskflow configuration

none

### What problem are you trying to solve?

none

### What solution do you propose?

none

**Comment by sithlord48** [comment]
There is a workflow for mac os 64. it needs mac os 13+ . 
https://github.com/deskflow/deskflow/actions/runs/11233930554/job/31228668055

**Comment by nbolton** [comment]
I re-ran the [original workflow](https://github.com/deskflow/deskflow/actions/runs/11141004285) as the artifacts for 1.17.0 had expired. I'll try to remember to upload it to the release.
