### ISSUE TITLE
W7: The procedure entry point CreateDXGIFactory2 could not be located

### ISSUE THREAD

**Issue by DavidBevi** [deskflow/deskflow#7627]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Windows 7 SP1

### Deskflow configuration

Default, I guess?

### What steps will reproduce the problem?

1. Install Deskflow
2. Reboot PC
3. Launch Deskflow
4. Get Error "The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll."

### Additional information

I cannot understand if Deskflow supports W7 in the first place, does it?

**Comment by sithlord48** [comment]
Windows 7 is not supported by Qt6.

**Comment by DavidBevi** [comment]
Also, you know, maybe you can say something like "Windows 7 is not supported by Qt6 **which is what makes Deskflow work**" so anyone can understand, and "**you can try to install [1.14.6.19-stable](https://github.com/deskflow/deskflow/releases/tag/1.14.6.19-stable) or prior**" (they used Qt5).

**Comment by nbolton** [comment]
Ah yes, sorry, we don't mean to be dismissive, we just have limited time and our community is made up of volunteers. Of course, you're welcome to use Synergy if you need an older version. Unlike Synergy, Deskflow's philosophy is to be leading edge and not support older versions.
