### ISSUE TITLE
Tray icon looks blurred/pixelated in kde plasma 6

### ISSUE THREAD

**Issue by mmsim6** [deskflow/deskflow#7630]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

Fedora 40, kde plasma 6, x11 session

### Deskflow configuration

Fedora linux server, Macos client

### What steps will reproduce the problem?

start deskflow and watch tray icon
![deskflow](https://github.com/user-attachments/assets/6014ff94-1c03-4ba2-bb04-d2af97b15540)

**Comment by sithlord48** [comment]
Yes icons sizes need to be fix I will add this to my todo list
