### ISSUE TITLE
Wayland access to clients stops when monitor layout changes on KDE 

### ISSUE THREAD

**Issue by gabeklavans** [deskflow/deskflow#7633]
### Project

Deskflow

### Deskflow version number

1.8.0

### Build type

Local developer build (built it yourself)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

- Fedora 40
- macOS 15.0

### Deskflow configuration

- Fedora 40 server
- macOS client to the left edge

### What steps will reproduce the problem?

1. Start deskflow, allowing clients to connect
2. Have 2 monitors, both enabled on server
3. Disable one of the monitors on the server

### Log output

```shell
[2024-10-09T23:39:50] DEBUG: portal cb disabled
```

### Additional information

KDE does not prompt me to allow the portal to capture input when this happens, but from the log it appears it has to do with the portal.

Stopping and restarting the deskflow server restarts the prompt flow and allows things to work again, without having to put the monitor config back to the way it was.

To be clear, this was not a problem under X11, and was something I did frequently without having to restart the server.

**Comment by sithlord48** [comment]
Sounds like a KDE bug please check https://bugs.kde.org and report there
