### ISSUE TITLE
Linter for conventional commit messages

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7643]
### Project

Deskflow

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] BSD-derived
- [X] Other

### OS versions/distros

n/a

### Deskflow configuration

n/a

### What problem are you trying to solve?

It's easy to forget to use or make a mistake with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### What solution do you propose?

CI should lint all commit messages in the PR and fail on any messages that are not valid.

**Comment by sithlord48** [comment]
I would not say we are using the "conventional commits"  scheme as much as using the fact that github will parse the prefixes the scheme uses to generate release notes. I don't think that we will have a point release for every `fix` for example.

**Comment by sithlord48** [comment]
We have decided we do not want to force the tags in all cases. 

If a several commits are used to make one 'fix' we don't need everyone to show the fix and we do not want to squash as it maybe easier to bisect errors later with smaller commits
