### ISSUE TITLE
Hyprland error: `No such interface “org.freedesktop.portal.RemoteDesktop”`

### ISSUE THREAD

**Issue by Azodox** [deskflow/deskflow#7646]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Community package (apt, dnf, brew, etc.)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [X] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

- Windows 11 server
- Arch Linux with Hyprland client

### Deskflow configuration

- Windows 11 server
- Arch Linux with Hyprland client

### What steps will reproduce the problem?

1. Start Deskflow
2. Try to connect to Windows Deskflow server

### Log output

```shell
[2024-10-12T15:24:54] INFO: starting core client process (desktop mode)
[2024-10-12T15:24:56] INFO: running command: /usr/bin/deskflow-client -f --no-tray --debug INFO --name luke-arch --enable-crypto --sync-language 192.168.1.52:24800
[2024-10-12T15:24:56] INFO: using ei screen for wayland
[2024-10-12T15:24:56] NOTE: started client
[2024-10-12T15:24:56] NOTE: connecting to '192.168.1.52': 192.168.1.52:24800
[2024-10-12T15:24:56] ERROR: failed to initialize remote desktop session: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.RemoteDesktop”
[2024-10-12T15:24:56] NOTE: stopped client
```

### Additional information

Not sure if it blocks everything but in my Windows Deskflow server output log, it reads it failed to accept secure socket with the following error:

`openssl error: error:0A000126:SSL routines:unexpected eof while reading`

**Comment by nbolton** [comment]
I think it's worthwhile making this issue Hyprland specific. I'm afraid it might be an upstream issue though, sadly.

**Comment by sithlord48** [comment]
Hyperland does not support the portals.. see https://github.com/deskflow/deskflow/discussions/7499

**Comment by nbolton** [comment]
@sithlord48 Is the 'not our bug' label relevant here?

**Comment by nbolton** [comment]
@feschber Hey, how did you get [lan-mouse](https://github.com/feschber/lan-mouse) working on Hyprland? I'm wondering if there's anything we need to do in Deskflow or if it's a wait-and-see game (for libportal). I'm guessing you're not going through libportal for Hyprland support? Looking at your chart, is Hyprland supported through wlroots? If so, AFAIK [synergy-micro-client-wayland](https://github.com/symless/synergy-micro-client-wayland) is done through wlroots. I wonder if Hyprland is ever going to be libportal compatible or if we need to implement wlroots support... 🙃 

| Desktop / Backend         | wlroots                  | libei                    | remote-desktop portal    | windows                  |   macos                                | x11                |
|---------------------------|--------------------------|--------------------------|--------------------------|--------------------------|----------------------------------------|--------------------|
| Wayland (wlroots)         | :heavy_check_mark:       |                          |                          |                          |                                        |                    |
| Wayland (KDE)             |                          | :heavy_check_mark:       | :heavy_check_mark:       |                          |                                        |                    |
| Wayland (Gnome)           |                          | :heavy_check_mark:       | :heavy_check_mark:       |                          |                                        |                    |
| Windows                   |                          |                          |                          | :heavy_check_mark:       |                                        |                    |
| MacOS                     |                          |                          |                          |                          |   :heavy_check_mark:                   |                    |
| X11                       |                          |                          |                          |                          |                                        | :heavy_check_mark: |

**Comment by sithlord48** [comment]
The entire point of portals is that they are stable and can be used by all desktops. wlroots needs to support the portals (iirc it predates the input capture /remote desktop portals). Long term its not sane to use a random desktops unstable interfaces.  Users can change the portal they are using as well.

**Comment by feschber** [comment]
@nbolton For input capture, I have a fallback interface that uses `wlr_layer_shell_v1` to construct 1px sized surfaces on the edges of screens:
https://github.com/feschber/lan-mouse/blob/b8063a813884b7444fe567deee8f61ff7931d351/input-capture/src/lib.rs#L302
https://github.com/feschber/lan-mouse/blob/b8063a813884b7444fe567deee8f61ff7931d351/input-capture/src/layer_shell.rs

As for input emulation I think Hyprland supports [`virtual-keyboard-unstable-v1`](https://wayland.app/protocols/virtual-keyboard-unstable-v1) and [`wlr-virtual-pointer-unstable-v1`](https://wayland.app/protocols/wlr-virtual-pointer-unstable-v1), which is also a fallback in input-emulation:
https://github.com/feschber/lan-mouse/blob/b8063a813884b7444fe567deee8f61ff7931d351/input-emulation/src/lib.rs#L113
(actually I prioritized the wlroots protocols for input-emulation, as they do not require user interaction through portals)
I have no idea what the current status of libei in Hyprland currently is, but this what made it work some time ago.

**Comment by nbolton** [comment]
@feschber Very helpful info, thank you.

**Comment by joanbarros** [comment]
So, will this be fixed eventually? are we waiting for something to be fixed upstream?

EDIT: Ok, I think I've read almost everything related to this issue, the fixes seem to be getting through into mainline release, although slowly.... I guess I can wait for the fixes to be released.

**Comment by sithlord48** [comment]
Hyperland currently only supports [Input Capture](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/259) and not [Remote Desktop](https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/252) there is no update needed in deskflow once a future version of hyperland supports remote desktop it should "just work" like it does on other backends that do support the portal
