### ISSUE TITLE
A fatal error has occured and the application must now exit (macOS)

### ISSUE THREAD

**Issue by mthomas184** [deskflow/deskflow#7663]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] BSD-derived
- [ ] Other

### OS versions/distros

macOS 15.0.1
Mac mini M2

### Deskflow configuration

macOS is the server. Windows is the client.
macOS is on the left with 2 screens and Windows is on the right with 2 screens.

### What steps will reproduce the problem?

Trying to launch Deskflow. Error comes up immediately and application shuts down.

### Log output

```shell
v1.17.0+r1 (44bd69fd)
command failed: /Applications/Deskflow.app/Contents/MacOS/deskflow-legacy --get-profile-dir
code: 0
error: none
```

**Comment by sithlord48** [comment]
Please try [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac) and report back.

**Comment by mthomas184** [comment]
So I had it set up originally and it was working without an issue then I randomly received that error. I re-installed the program and it is now working. So I am unsure what caused the issue but a re-install seemed to have fixed it.

**Comment by nbolton** [comment]
Alright, tentatively closing in that case. Thanks for updating us.
