### ISSUE TITLE
Migrate Meson dependency fetching to CMake (FetchContent)

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7679]
### What problem are you trying to solve?

As discussed (#7546) using Meson to get deps was a mistake.

### What solution do you propose?

Use CMake `FetchContent` instead and remove our `Meson` config entirely.

**Comment by sithlord48** [comment]
correct

**Comment by sithlord48** [comment]
These landed and remove cli11 and tomlplusplus from meson
#7744  #7745

**Comment by nbolton** [comment]
> These landed and remove cli11 and tomlplusplus from meson #7744 #7745

Excellent work.

**Comment by sithlord48** [comment]
In #7750 we removed the need for meson for windows completely. 
#7764  Furthers this goal a bit more
