### ISSUE TITLE
Selectable version number for easy copy/paste

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7722]
### Project

Deskflow

### What problem are you trying to solve?

When reporting a bug, I have to type the version number manually increasing the potential for a typo.

### What solution do you propose?

Make the version number text selectable so I can copy/paste it... or better still, also add a one-click copy button next to it.

![image](https://github.com/user-attachments/assets/15ac50d1-a85f-43cd-b3a3-8670d551049c)

**Comment by sithlord48** [comment]
i can do this quick

**Comment by sithlord48** [comment]
> or better still, also add a one-click copy button next to it.

I will highly consider this when I redo the dialogs UI file.

**Comment by nbolton** [comment]
> > or better still, also add a one-click copy button next to it.
> 
> I will do this when I redo the dialogs UI file. (but i don't want todo before then)

Sure, that's definitely a nice to have.

Copy/paste version is a should have I think. Glad it's in!
