### ISSUE TITLE
Nitpick: cmake log should not use caps

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7727]
### Project

Deskflow

### What problem are you trying to solve?

The CMake log has become very shouty and is distracting. Rage comments degrade SNR and make for poor readability. Log output should be consistent.

**Hacking Guide:** [No rage caps in comments/logs](https://github.com/deskflow/deskflow/wiki/Hacking-Guide#4-no-rage-caps-in-commentslogs)

### What solution do you propose?

Replace shouty log lines with more polite and respectful ones.

### CMake output
```
[cmake] -- Appending code coverage compiler flags: -g -fprofile-arcs -ftest-coverage
[cmake] -- tomlplusplus version: 3.4.0
[cmake] -- CLI11 version: 2.4.1
[cmake] -- DISTRO NAME: debian
[cmake] -- DISTRO LIKE: 
[cmake] -- DISTRO CODENAME: trixie
[cmake] -- DISTRO ID: 
[cmake] -- DEB RELEASE INFO: 1~trixie
[cmake] -- OS INFO: debian-trixie-x86_64
[cmake] -- Configuring done (0.3s)
[cmake] -- Generating done (0.1s)
[cmake] -- Build files have been written to: /home/nick/Projects/deskflow/build
````

**Comment by sithlord48** [comment]
changed the title to reflect more what this really is a nit pick about caps in logs.

**Comment by sithlord48** [comment]
again those item in caps are there to be stand out in the log.

**Comment by sithlord48** [comment]
`[cmake] -- CLI11 version: 2.4.1`
that is the name of the component how do u uncaps that ?

**Comment by nbolton** [comment]
> `[cmake] -- CLI11 version: 2.4.1` that is the name of the component how do u uncaps that ?

Names are an exception; this doesn't jump out because that's how it normally looks.

**Comment by nbolton** [comment]
> changed the title to reflect more what this really is a nit pick about caps in logs.

I'm at serious risk of coining a new phrase here: _Nick-picking_ :wink:

**Comment by sithlord48** [comment]
> > changed the title to reflect more what this really is a nit pick about caps in logs.
> 
> I'm at serious risk of coining a new phrase here: _Nick-picking_ 😉

Sounds like a new issue type for the project :p
