### ISSUE TITLE
Fatal error on macOS due to libtomlplusplus.3.dylib

### ISSUE THREAD

**Issue by mmsim6** [deskflow/deskflow#7759]
### Project

Deskflow

### Deskflow version number

1.17.0.86

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland known issues and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- MacOS 15

### What steps will reproduce the problem?

1. Start deskflow
<img width="868" alt="378061420-45160b08-48ab-42f0-b441-4ee276f2f3ca" src="https://github.com/user-attachments/assets/e93d0a8c-3e31-417a-bf61-dd6b5ece2dde">

**Comment by nbolton** [comment]
> @sithlord48 We probably need to bundle or static link TOML++ and CLI11 on macOS :(

**Comment by nbolton** [comment]
Or we could static link them like we do with OpenSSL. Not sure if that's nasty though. Means you can't update it but also Apple doesn't let you change signed bundles anyway.
