### ISSUE TITLE
Change release owner to GitHub machine user

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7773]
### Feature Request

To the outside observer it looks like I'm creating releases, which is not the case as this is automated by CI.

![image](https://github.com/user-attachments/assets/aa874028-47ef-4623-a824-6fe3bc2a72b3)

I intend to create a "[machine user](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#:~:text=is%20called%20a-,machine%20user,-.%20For%20example%2C%20you)" to do this. The alternative is to use a GitHub app, which I may also investigate.

**Comment by nbolton** [comment]
I'll take care of it.

**Comment by sithlord48** [comment]
Making a requirement for 1.18.0
