### ISSUE TITLE
Error: `libei is not supported` (Ubuntu 24.04)

### ISSUE THREAD

**Issue by poo0054** [deskflow/deskflow#7797]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [x] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [X] I am unable to try the latest continuous build

### OS versions/distros

ubuntu24 4

### What steps will reproduce the problem?

I am a newbie. I am using Ubuntu 24.4. I downloaded deskflow and it says ·libei is not supported · What should I do? I found libei in gitlab, but there is no installation tutorial. Where can I install it or where can I view the documentation?

I have seen this problem in #7733 and #4090. But I don't know how to solve it. Can anyone help me?

**Comment by nbolton** [comment]
Did you try the [stable release of v1.17.0](https://github.com/deskflow/deskflow/releases/tag/v1.17.0) or the continuous build?

The stable release has `libportal` 0.8 static linked (which is normally not available on Ubuntu 24.04). The continuous builds no longer have `libportal` static linked, and therefore it uses the now very old `libportal` 0.7 that ships with Ubuntu 24.04. We are currently waiting for Canonical to catch up to Debian Trixie (which does have `libportal` 0.8).

**Comment by poo0054** [comment]
I have tried both the stable version and the latest build. The latest build I found is 0.8. What I don't understand now is that there are various *libportal* in this page. `https://launchpad.net/ubuntu/+source/libportal`
I don't quite understand which one of libportal-dev/test and ibportal1 I should download. Or where. I found the version in `https://github.com/deskflow/deskflow/pull/7597`. But this libportal has many suffixes. This makes me a little confused.
`https://gitlab.freedesktop.org/libinput/libei/-/releases/1.3.0` I also found the version here, but is there any difference with `ibportal1`?
I am a newbie and I can say that I don't understand this at all. Thank you very much for answering me.
I just tried to start deskflow on ubuntu24.4, but now I don't know what to do to start it normally. I think my Ubuntu system got damaged when I installed this version, and now the visualization page of Ubuntu cannot be displayed.

**Comment by poo0054** [comment]
My Ubuntu has been updated.
apt update
apt upgrade

**Comment by nbolton** [comment]
> tried the stable version

Could you let me know the filename of the Deskflow package you installed?

**Comment by poo0054** [comment]
deskflow_1.17.0+r1_ubuntu-24-04_amd64.deb
deskflow_1.17.0.125-1.trixie_amd64.deb
When I installed `deskflow_1.17.0.125-1.trixie_amd64.deb`, I needed version 0.8. Then my ubuntu broke.
When installing `deskflow_1.17.0+r1_ubuntu-24-04_amd64.deb`, it showed libei is not supported

**Comment by nbolton** [comment]
> When installing `deskflow_1.17.0+r1_ubuntu-24-04_amd64.deb`, it showed libei is not supported

Hmm. I wonder what version of libei you had installed at that point. Looks like 24.04 comes with libei 1.2.1 which definitely works (I tested this myself). Do you think it's possible that you updated your system after trying this and then tried the continuous build?

**Comment by nbolton** [comment]
Well that's odd. I think perhaps I tested Deskflow v1.16 which definitely worked (but the download has gone for now), it seems that indeed 1.17 is not working with Ubuntu 24.04. I'll get to work on a solution.

Sorry about that!

**Comment by poo0054** [comment]
I am very grateful to your open source community. I just have a question and I don't know if you can answer it for me. How can I download `libei` in Ubuntu, that is, what is the relationship between `libportal` libportal-dev/libportal-devtest and others? Which version should I modify to use the latest version?

**Comment by nbolton** [comment]
> I am very grateful to your open source community. 

We're grateful for you! Thanks for testing and reporting bugs.

> How can I download `libei` in Ubuntu?
> Which version should I modify to use the latest version?

Don't worry about that. You already have `libei` 1.2 which is sufficient. We bumped out min required `libei` version to 1.3, which was a mistake in hindsight as `libei` 1.2 works just fine.

I prepared some Ubuntu 24.04 build instructions with a patch to fix this in 1.17.0: https://github.com/deskflow/deskflow/discussions/7499#discussioncomment-11027553

I'll upload a new package for v1.17.0 soon to replace the existing Ubuntu 24.04 package. It will link against `libei` 1.2 instead of not linking against `libei` (which is the current issue).

> what is the relationship between `libportal` libportal-dev/libportal-devtest and others? 

Don't worry about that either. I'll get you a solution. Ubuntu 24.04 only has `libportal` 0.7 available which is too old for Deskflow to work fully with server and client Wayland support, so we don't even bother linking against it. Instead, we do something really hacky which is to link against `libportal` 0.8 which we build ourselves... super hacky but it's the only way to get Deskflow working with Wayland on Ubuntu 24.04.

Working on the new package now, hold on.

**Comment by sithlord48** [comment]
Ask your distro to update their packages , use an older version  or wait until we have a working flatpak

**Comment by nbolton** [comment]
> Ask your distro to update their packages

I raised a bug report: https://bugs.launchpad.net/ubuntu/+source/libportal/+bug/2085424

**Comment by poo0054** [comment]
Thank you very much for the open source community.
I have now switched to Windows 11, and I will close this question after this problem is solved.
Thank you very much, I am currently using the macos and windows versions, and it supports both macos and windows perfectly. I wanted to support your commercial version, but all my bank cards cannot pay. If you can go online in China (you can use Alipay and WeChat), I will definitely support you. Thank you very much for this open source project
