### ISSUE TITLE
Add Deskflow to winget packages repository

### ISSUE THREAD

**Issue by nicola02nb** [deskflow/deskflow#7808]
### Feature Request

Since I started using UniGetUI for managing most of my windows updates, it would be veri cool to get also deskflow updates through winget package manager. 

If needed I can create the first starting manifest with the latest release, but to keep the package updated, it requirese or a manual submission at every update or an automated CI that does that([winget-updater](https://github.com/marketplace/actions/winget-updater) should do the job).

**Comment by sithlord48** [comment]
Please do see if you can integrate this into our ci jobs. 
We release on tags of `v*` and we have a  `continuous` tag that is always the current code as it lands into our master branch
 
Currently our package names are  `deskflow_1.17.0.133_windows_x64.msi`

At the release of 1.18.0, the windows install will be named `deskflow-1.18.0.0-win64.msi`

**Comment by nicola02nb** [comment]
Created PR #7811
Let me know if it could work
