### ISSUE TITLE
Synergy 1 Pro Beta Bug Report Link

### ISSUE THREAD

**Issue by bigbear3001** [deskflow/deskflow#7809]
### Project

Synergy

### Deskflow version number

1.16.1-beta+r1

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Ubuntu 24.04

### Deskflow configuration

- Ubuntu 24.04 Server + Client
- Server 2 Screens 
- Client 1 Screen

### What steps will reproduce the problem?

* Start syngery beta
*  report bugs goes to https://github.com/symless/synergy/issues which redirects to https://github.com/symless/synergy/pulls

### Additional information

Should the report bugs go to https://github.com/deskflow/deskflow/issues?

**Comment by nbolton** [comment]
Thanks for the report, I'll get this fixed downstream in Synergy (I have opened it in our internal tracker).
