### ISSUE TITLE
Can not run in macos 15.0.1

### ISSUE THREAD

**Issue by MrR0990** [deskflow/deskflow#7812]
### Project

Deskflow

### Deskflow version number

1.17.0.148

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macos 15.0.1

### Deskflow configuration

only macos

### What steps will reproduce the problem?

1. start deskflow

### Additional information

![image](https://github.com/user-attachments/assets/46be632b-eb1a-4f38-b67a-6132248fb8fa)

**Comment by nbolton** [comment]
I believe this is a duplicate issue of: #7606

Please go there and follow the instructions. Thanks!
