### ISSUE TITLE
Unable to run/authorise ARM64 build of Deskflow on macOS 15.0.1, M1 Apple Silicon (but Intel x64 build works)

### ISSUE THREAD

**Issue by DominikDeak** [deskflow/deskflow#7817]
### Project

Deskflow

### Deskflow version number

 v1.17.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

 macOS 15.0.1, M1 Apple Silicon

### Deskflow configuration

- Windows 10 server,  macOS 15.0.1 client
- Both are single screens 

### What steps will reproduce the problem?

1. Download `deskflow_1.17.0.149_mac_arm64.dmg`
2. Mount with Finder, drag/drop `Deskflow.app` into `Applications` folder
3. Try to run `Deskflow.app`
4. This message appears: _"Deskflow.app" is damaged and can't be opened. You should move it to the Bin._
5. Follow [Apple's instructions](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac) and try authorise the app
6. Unfortunately, the "Open Anyway" button for Deskflow in the "Privacy & Security" is absent and unable to continue with the authorisation process.

### Additional information

This issue seems to affect to ARM64 binaries only. If I were to download Intel x64 build, (`deskflow_1.17.0.149_mac_x64.dmg`), the above authorisation process works.

**Comment by sithlord48** [comment]
interesting.. 
can you try `xattr -c Deskflow.app` on the arm one and see if that makes it work . i've had to do this for just about all non store (non brew) apps i've downlaoded since the os15 update.

**Comment by DominikDeak** [comment]
@sithlord48 Yes, that did the trick.

**Comment by sithlord48** [comment]
I tried to do it on ci but that does not work it has to happen on your machine.

**Comment by DominikDeak** [comment]
I figured that might be the case. Just to clarify, I meant automating the authorisation step somehow while the user is deploying the app on the machine from the `dmg` archive. For example, include an installer script in the `dmg` archive that copies the app into the `Applications` folder and then runs the `xattr` utility. Perhaps there is a better way of doing this. Just a random thought.

**Comment by sithlord48** [comment]
If your gonna ship a script then dmg is not the proper installer format anymore and pkg files are what you want.

**Comment by emircanerkul** [comment]
+1 I also faced same issue

**Comment by sithlord48** [comment]
Making as "not our issue" Since its not our problem apple forces this even more now. There are several Duplicates of this so don't worry we are aware of it .
