### ISSUE TITLE
Not working on Fedora 40 with libportal 0.8 installed

### ISSUE THREAD

**Issue by markusdd** [deskflow/deskflow#7829]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Nobara 40 (essentially Fedora 40 with KDE for this purpose here)

### Deskflow configuration

no config yet as it complains already on startup

### What steps will reproduce the problem?

try to use it on Nobara 40 I guess?

### Log output

```shell
[2024-10-29T22:14:22] INFO: starting core server process (desktop mode)
[2024-10-29T22:14:22] WARNING: missing required wayland lib(s) or feature
[2024-10-29T22:14:22] DEBUG: configuration read successfully
[2024-10-29T22:14:22] INFO: using ei screen for wayland
[2024-10-29T22:14:22] DEBUG: adopting new buffer
[2024-10-29T22:14:22] DEBUG: adopting new buffer
[2024-10-29T22:14:22] FATAL: an error occurred: missing libportal input capture support
```

### Additional information

dnf list installed | grep libportal
libportal.x86_64                                      0.8.1-1.fc40                                     @updates       

I would claim that a supported libportal is installed.
Any other libportal depedencies that are needed? The log is unfortunately not helpful as it is not specifying which exact .so it is trying to find. Checking deskflow binary with ldd does not show libportal, so it is not possibel to know where it is looking.

**Comment by markusdd** [comment]
plasma is at 6.2.2

the portal package is this:
xdg-desktop-portal-kde-6.2.2-1.fc40.x86_64

**Comment by sithlord48** [comment]
those should work

**Comment by markusdd** [comment]
yeah they don't, it still complains with the same messages :(

**Comment by shymega** [comment]
Can you provide logs from journald - but filter on units `xdg-desktop-portal-kde` and `xdg-desktop-portal`, and then try and reproduce the connection process?

**Comment by nbolton** [comment]
I threw this error when the binary is not linked against `libei`:
```
[2024-10-29T22:14:22] FATAL: an error occurred: missing libportal input capture support
```
https://github.com/deskflow/deskflow/blame/8beeaf42763da02cd13672222f5f632907d43119/src/lib/platform/EiScreen.cpp#L74

However, this has been removed from `master` as `libei` is not a required lib: 7b7ff81a9fa270cedabaea8e0b6b4360a5787ee3

I think the issue here is perhaps that our [stable v1.17.0](https://github.com/deskflow/deskflow/releases/tag/v1.17.0) Fedora 40 RPM is not built against `libei` for some reason.

I'll take a look at the package and get back to you.

**Comment by nbolton** [comment]
> I'll cook up a fresh RPM for you that links against `libportal` 0.8.

@markusdd Ok give this a shot: [deskflow_1.17.0-2_fedora-40_amd64.rpm](https://github.com/deskflow/deskflow/releases/download/v1.17.0/deskflow_1.17.0-2_fedora-40_amd64.rpm)

**Comment by markusdd** [comment]
Hi, thanks so much for looking into this.

I can try the continuous when I have access to my desktop machine again, I'm traveling until Sunday. I will try as soon as I'm back!

**Comment by markusdd** [comment]
Hi, I can confirm the updated 1.17.0 release you uploaded 3 days ago is now working flawlessly!

Thanks so much for the quick fix, cheers!
