### ISSUE TITLE
Desklow window crashes/quits when opening `Help -> About Deskflow...` menu item

### ISSUE THREAD

**Issue by DominikDeak** [deskflow/deskflow#7842]
### Project

Deskflow

### Deskflow version number

1.17.0.166

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Windows 10

### Deskflow configuration

Windows 10 server
macOS 15.1 client

### What steps will reproduce the problem?

1. Open Deskflow main window
2. Go into Help menu -> About Deskflow...
3. Crash

### Log output

```shell
Faulting application name: deskflow.exe, version: 1.17.0.166, time stamp: 0x67237c3e
Faulting module name: MSVCP140.dll, version: 14.32.31326.0, time stamp: 0x7255e0ca
Exception code: 0xc0000005
Fault offset: 0x0000000000013278
Faulting process id: 0x2ae0
Faulting application start time: 0x01db2bfccf63de9d
Faulting application path: C:\Program Files\Deskflow\deskflow.exe
Faulting module path: C:\Windows\SYSTEM32\MSVCP140.dll
Report Id: 80d9a7ab-22b8-4b59-91f8-704aebfe9894
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by nbolton** [comment]
Interesting. So we're almost ready to land #7836 which could fix this.

**Comment by DominikDeak** [comment]
Yep, build 1.17.0.170 (8977f28b) fixes this issue. Cheers.
