### ISSUE TITLE
Can't open configure window on Linux

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [deskflow/deskflow#7859]
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [X] I am unable to try the latest continuous build

### OS versions/distros

Linux fedora 6.11.5-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024 x86_64 GNU/Linux

Fedora 41

### Deskflow configuration

Linux Gnome Wayland - server
Windows 10 - client. Basic setup

### What steps will reproduce the problem?

1. Start deskflow
2. Select server mode
3. Click "Configure"

**Comment by muhammadyusuf-kurbonov** [comment]
Fixed in continuous [deskflow-1.17.0.173-fedora_41_x86_64.rpm](https://github.com/deskflow/deskflow/releases/download/continuous/deskflow-1.17.0.173-fedora_41_x86_64.rpm)

**Comment by nbolton** [comment]
Excellent! Thanks for reporting that.
