### ISSUE TITLE
fail to install on ubuntu 22.04

### ISSUE THREAD

**Issue by verigle** [deskflow/deskflow#7867]
### Project

Deskflow

### Deskflow version number

deskflow-1.17.0.0-2_ubuntu_noble_amd64.deb

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [X] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

ubuntu 22.04

### Deskflow configuration

deskflow-1.17.0.0-2_ubuntu_noble_amd64.deb

### What steps will reproduce the problem?

sudo dpkg -i deskflow-1.17.0.0-2_ubuntu_noble_amd64.deb

### Log output

```shell
sudo dpkg -i deskflow-1.17.0.0-2_ubuntu_noble_amd64.deb 
(正在读取数据库 ... 系统当前共安装有 281900 个文件和目录。)
准备解压 deskflow-1.17.0.0-2_ubuntu_noble_amd64.deb  ...
正在解压 deskflow (1.17.0) 并覆盖 (1.17.0) ...
dpkg: 依赖关系问题使得 deskflow 的配置工作不能继续：
 deskflow 依赖于 libc6 (>= 2.38)；然而：
系统中 libc6:amd64 的版本为 2.35-0ubuntu3.8。
 deskflow 依赖于 libei1 (>= 1.0.0)；然而：
  未安装软件包 libei1。
 deskflow 依赖于 libglib2.0-0t64 (>= 2.79.0)；然而：
  未安装软件包 libglib2.0-0t64。
 deskflow 依赖于 libqt6core6t64 (>= 6.4.0)；然而：
  未安装软件包 libqt6core6t64。
 deskflow 依赖于 libqt6dbus6t64 (>= 6.4.0)；然而：
  未安装软件包 libqt6dbus6t64。
 deskflow 依赖于 libqt6gui6t64 (>= 6.1.2)；然而：
  未安装软件包 libqt6gui6t64。
 deskflow 依赖于 libqt6network6t64 (>= 6.4.0)；然而：
  未安装软件包 libqt6network6t64。
 deskflow 依赖于 libqt6widgets6t64 (>= 6.1.2)；然而：
  未安装软件包 libqt6widgets6t64。
 deskflow 依赖于 libssl3t64 (>= 3.0.0)；然而：
  未安装软件包 libssl3t64。
 deskflow 依赖于 libstdc++6 (>= 13.1)；然而：
系统中 libstdc++6:amd64 的版本为 12.3.0-1ubuntu1~22.04。

dpkg: 处理软件包 deskflow (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 mailcap (3.70+nmu1ubuntu1) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1ubuntu3) 的触发器 ...
正在处理用于 desktop-file-utils (0.26-1ubuntu3) 的触发器 ...
在处理时有错误发生：
 deskflow
```

**Comment by nbolton** [comment]
Hello, thanks for reporting a bug. Unfortunately, we do not have an Ubuntu 22 build. Please upgrade to Ubuntu 24 or later.

**Comment by verigle** [comment]
is there any plan to release binary for ubuntu 24.04

**Comment by nbolton** [comment]
Unfortunately not, but there will be a package for Ubuntu 25.04: #7884

**Comment by beccon4** [comment]
Probably installing via Flatpak is an alternative:
https://flathub.org/apps/org.deskflow.deskflow

**Comment by TT2TER** [comment]
> Probably installing via Flatpak is an alternative: https://flathub.org/apps/org.deskflow.deskflow

this works for me
