### ISSUE TITLE
assistive devices does not trust this process

### ISSUE THREAD

**Issue by wheesys** [deskflow/deskflow#7868]
### Project

Deskflow

### Deskflow version number

1.17.0+r1

### Build type

Community package (apt, dnf, brew, etc.)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [x] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [x] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.1

### Deskflow configuration

I add homebrew tab and install.
I use macOS 15.1 as server, and when I start deskflow, get this alert.
_INFO: running command: /Applications/Deskflow.app/Contents/MacOS/deskflow-server -f --no-tray --debug INFO --name *** --enable-crypto --address :24800 -c /Users/***/Library/Preferences/Deskflow/deskflow-server.conf --tls-cert /Users/***/Library/Deskflow/SSL/Deskflow.pem
[2024-11-07T16:47:21] FATAL: a runtime error occurred: assistive devices does not trust this process, allow it in system settings.
[2024-11-07T16:47:21] WARNING: desktop process exited with error code: 1_
I noticed the homepage prompt
_When you install Deskflow on macOS, you need to allow accessibility access (Privacy & Security) to both the Deskflow app and the deskflow process._
how can i allow the deskflow process?

this fix my problem ,https://github.com/deskflow/deskflow/issues/7868#issuecomment-2462354628

**Comment by sithlord48** [comment]
It says it right in the error 

`FATAL: a runtime error occurred: assistive devices does not trust this process, allow it in system settings.`

From our readme: 

>If you are upgrading and you already have Deskflow or deskflow on the allowed list you will need to manually remove them before accessibility access can be granted to the new version.

**Comment by Trouffman** [comment]
This is a common & recurring issue.

Even after proceeding as required. 
Step reproduced :
- In system settings -> privacy and security -> accessibility
- Delete deskflow
- click "+" and add Deskflow again
- Enable Deskflow

![image](https://github.com/user-attachments/assets/05333e8b-36a1-4a31-bb8e-4eeb3685cd3b)

How to add the "deskflow-server" to this menu ?

**Comment by sithlord48** [comment]
When you start it form the gui you should get a prompt from mac os to add it. if not you need to use the + to add it , you will need to browse inside the Deskflow.app bundle to find the deskflow executable in iirc

**Comment by sithlord48** [comment]
> This is a common & recurring issue.

Mac Os' Security model is working exactly as they planed it.

I am looking into how to add / remove those as part of the brew install so eventually its not as annoying.

**Comment by Trouffman** [comment]
I have the same issue with a couple other Open source project.

FYI this is not obvious how to "add the deskflow process" to the Privacy & security settings because the defualt finder does not allow to go inside the package and select a specific process.
![image](https://github.com/user-attachments/assets/72864ea4-37a9-41ed-97a2-cf9595ed9b0f)



For MacOS here is how to solve that issue and allow the deskflow "process". 

1. Go in to system settings -> privacy and security -> accessibility
2. Open Finder. Go to Applications, right-click on 'Deskflow' -> Show Package Content
![image](https://github.com/user-attachments/assets/7f0dce4d-ea18-480b-9420-540538a227be)

3. Go to Contents -> MacOS
4. Drag & Drop the file `deskflow` into the Accessiblity settings windows (opened in Step 1)
5. Enable both deskflow options

![image](https://github.com/user-attachments/assets/081f156a-e702-457c-922e-1fddf3648a49)

**Comment by sithlord48** [comment]
^ Should go in to our wiki on common issues ! 
Great explanation @Trouffman !!!

**Comment by wheesys** [comment]
> It says it right in the error它在错误中说得对
> 
> `FATAL: a runtime error occurred: assistive devices does not trust this process, allow it in system settings.`
> 
> From our readme: 来自我们的自述文件：
> 
> > If you are upgrading and you already have Deskflow or deskflow on the allowed list you will need to manually remove them before accessibility access can be granted to the new version.如果您正在升级并且已在允许列表中添加了 Deskflow 或 deskflow，则您需要手动删除它们，然后才能向新版本授予辅助功能访问权限。
> 
> Go in to system settings -> privacy and security -> accessibility进入系统设置 -> 隐私和安全 -> 辅助功能
> 
> if you see deskflow on enable it if not use teh + to add it to the list. if its already on the list remove it then re add it如果您看到 deskflow 已打开，请启用它，如果没有，请使用 + 将其添加到列表中。如果它已经在列表中，请将其删除然后重新添加

first, I'm installing for the first time.
and, I have tried the steps you mentioned.

**Comment by wheesys** [comment]
> It says it right in the error
> 
> `FATAL: a runtime error occurred: assistive devices does not trust this process, allow it in system settings.`
> 
> From our readme:
> 
> > If you are upgrading and you already have Deskflow or deskflow on the allowed list you will need to manually remove them before accessibility access can be granted to the new version.
> 
> Go in to system settings -> privacy and security -> accessibility
> 
> if you see deskflow on enable it if not use teh + to add it to the list. if its already on the list remove it then re add it

first, I'm installing for the first time.
and, I have tried the steps you mentioned.

**Comment by wheesys** [comment]
> It says it right in the error
> 
> `FATAL: a runtime error occurred: assistive devices does not trust this process, allow it in system settings.`
> 
> From our readme:
> 
> > If you are upgrading and you already have Deskflow or deskflow on the allowed list you will need to manually remove them before accessibility access can be granted to the new version.
> 
> Go in to system settings -> privacy and security -> accessibility
> 
> if you see deskflow on enable it if not use teh + to add it to the list. if its already on the list remove it then re add it

first, I'm installing for the first time.
and, I have tried the steps you mentioned.

> This is a common & recurring issue.
> 
> Even after proceeding as required. Step reproduced :
> 
> * In system settings -> privacy and security -> accessibility
> * Delete deskflow
> * click "+" and add Deskflow again
> * Enable Deskflow
> 
> ![image](https://private-user-images.githubusercontent.com/2151317/383982559-05333e8b-36a1-4a31-bb8e-4eeb3685cd3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzEwMzQsIm5iZiI6MTczMTAzMDczNCwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk4MjU1OS0wNTMzM2U4Yi0zNmExLTRhMzEtYmI4ZS00ZWViMzY4NWNkM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1MjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIwZTBhODRiNDEyZjc4NDNhMjg5NGI2MTZlYWVlMmVkMzkxOWQxYzU3MTgxNDYxMjhhZGZlOGM5YjNhOGYwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TZLMVPWv35mbHNkAiwISTYgBD4X2-OrmcTK3OT00Yc8)
> 
> How to add the "deskflow-server" to this menu ?

yes, this is my problem.

**Comment by wheesys** [comment]
> I have the same issue with a couple other Open source project.我对其他几个开源项目也有同样的问题。
> 
> FYI this is not obvious how to "add the deskflow process" to the Privacy & security settings because the defualt finder does not allow to go inside the package and select a specific process.仅供参考，如何将 deskflow 进程“添加到隐私和安全设置”并不明显，因为默认查找器不允许进入包内部并选择特定进程。 ![image](https://private-user-images.githubusercontent.com/2151317/383994868-72864ea4-37a9-41ed-97a2-cf9595ed9b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzExNjUsIm5iZiI6MTczMTAzMDg2NSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NDg2OC03Mjg2NGVhNC0zN2E5LTQxZWQtOTdhMi1jZjk1OTVlZDliMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFhZDE2ODllZTI3NGFkZDI2ZDMyOTgxNWEzYzQ2YmRjYWU3YTY4ZjA0MTEzZjUzNThkZTMxMzVlN2Y5ZDRkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VA2Dg8-qgC1HEfZlKzmqm7BJdZrNL2qnYksFn5ajWO4)
> 
> For MacOS here is how to solve that issue and allow the deskflow "process".对于 MacOS，这里介绍了如何解决该问题并允许桌面流“处理”。
> 
> 1. Go in to system settings -> privacy and security -> accessibility进入系统设置 -> 隐私和安全 -> 辅助功能
> 2. Open Finder. Go to Applications, right-click on 'Deskflow' -> Show Package Content打开查找器。转到“应用程序”，右键单击“Deskflow”-> 显示包内容
>    ![image](https://private-user-images.githubusercontent.com/2151317/383995649-7f0dce4d-ea18-480b-9420-540538a227be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzExNjUsIm5iZiI6MTczMTAzMDg2NSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NTY0OS03ZjBkY2U0ZC1lYTE4LTQ4MGItOTQyMC01NDA1MzhhMjI3YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQwMjQ0OTQ3NTFhMWFiYmY4YTUwYTg3MzE3ZDM1MTQ4YTJlODU2MzU5ZDgwNWJmNDAxZTc1NWQ4NjRkNjBlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hUKZrk8elOXU9Xv1LQFFOGrJQin-Rk3vzfToGcuMS74)
> 3. Go to Contents -> MacOS转到目录 -> MacOS
> 4. Drag & Drop the file `deskflow` into the Accessiblity settings windows (opened in Step 1)将文件`deskflow`拖放到辅助功能设置窗口（在步骤 1 中打开）
> 5. Enable both deskflow options启用两个桌面流程选项
> 
> ![image](https://private-user-images.githubusercontent.com/2151317/383996303-081f156a-e702-457c-922e-1fddf3648a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzExNjUsIm5iZiI6MTczMTAzMDg2NSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NjMwMy0wODFmMTU2YS1lNzAyLTQ1N2MtOTIyZS0xZmRkZjM2NDhhNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZmYWFiNmU5NDJiODA2NjE2MjkxYjUzNzY2MTNiYzc3MGQxMWVhZjRkNTM0ZjE0OTUzMWY2ZjY1MGVhMzU5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3_SaF2N4iRaXKhfMBZ6NUY42V9b_qKKa-L2SSWZM2NE)

you are right, this solved

**Comment by wheesys** [comment]
> I have the same issue with a couple other Open source project.
> 
> FYI this is not obvious how to "add the deskflow process" to the Privacy & security settings because the defualt finder does not allow to go inside the package and select a specific process. ![image](https://private-user-images.githubusercontent.com/2151317/383994868-72864ea4-37a9-41ed-97a2-cf9595ed9b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzEyNjQsIm5iZiI6MTczMTAzMDk2NCwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NDg2OC03Mjg2NGVhNC0zN2E5LTQxZWQtOTdhMi1jZjk1OTVlZDliMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcyNzcxYTY1YmE5ZTc5YzdlN2VhYTNmZTZiODg1ZDY1NDgwZGYzNWUwMWY0MjY5OWY3YjU5ZmZhYzc3ZWI2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GoyXS6sixs8v6fBZxCyL2CWNbrCnVLGNyOugWlKT9Lw)
> 
> For MacOS here is how to solve that issue and allow the deskflow "process".
> 
> 1. Go in to system settings -> privacy and security -> accessibility
> 2. Open Finder. Go to Applications, right-click on 'Deskflow' -> Show Package Content
>    ![image](https://private-user-images.githubusercontent.com/2151317/383995649-7f0dce4d-ea18-480b-9420-540538a227be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzEyNjQsIm5iZiI6MTczMTAzMDk2NCwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NTY0OS03ZjBkY2U0ZC1lYTE4LTQ4MGItOTQyMC01NDA1MzhhMjI3YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEyNTAxYWI1NDZjN2FlNTFlZjcwODgzYmZmNzhjOWI4OWRhMmQ2YzIzYjE2YmM2YzkyMDZjZjY5YmNiOTg0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JseIcigLs5ErN2sPgckvor38MNnlViaHuWUK6GFSMR4)
> 3. Go to Contents -> MacOS
> 4. Drag & Drop the file `deskflow` into the Accessiblity settings windows (opened in Step 1)
> 5. Enable both deskflow options
> 
> ![image](https://private-user-images.githubusercontent.com/2151317/383996303-081f156a-e702-457c-922e-1fddf3648a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzEyNjQsIm5iZiI6MTczMTAzMDk2NCwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NjMwMy0wODFmMTU2YS1lNzAyLTQ1N2MtOTIyZS0xZmRkZjM2NDhhNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDE1NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM2ZGQ2ZDJmMDlkNTU3NzZmZWQ1ZTEzYzdjN2EyOWE5NTEyN2FiNzhkYmZhMDc3NGMwNjQ4ZjlkNGNjODYyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dKq4J-YQpZarFnyE6inVDoyoothNlPNdBg5F-fNdH1s)

you are right, this solved

**Comment by sithlord48** [comment]
Added above to the [workarounds](https://github.com/deskflow/deskflow/wiki/Workarounds) wiki page.

**Comment by xueleilei** [comment]
> 我对其他几个开源项目也遇到了同样的问题。
> 
> 仅供参考，如何将 deskflow 流程添加到隐私和安全设置中并不明显，因为默认查找器不允许进入包内部并选择特定流程。 ![图像](https://private-user-images.githubusercontent.com/2151317/383994868-72864ea4-37a9-41ed-97a2-cf9595ed9b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjg3MzksIm5iZiI6MTczNDkyODQzOSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NDg2OC03Mjg2NGVhNC0zN2E5LTQxZWQtOTdhMi1jZjk1OTVlZDliMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDQzMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE1ZmM3MDRhNzlhMjA5ZjQ5Y2M2ZjdiMjNkNGFiMmU5ZjI0Y2QzNWQ0ZTM0NTk4Y2MwNzdjN2RjNGZiOWVmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eTIXndfqziJEZdpPqZ_w2v0jNuChJ2UuLEBan_HIzFU)
> 
> 对于 MacOS，这里介绍了如何解决该问题并允许 deskflow“处理”。
> 
> 1. 进入系统设置->隐私和安全->辅助功能
> 2. 打开 Finder。转到应用程序，右键单击“Deskflow”-> 显示包内容
>    ![图像](https://private-user-images.githubusercontent.com/2151317/383995649-7f0dce4d-ea18-480b-9420-540538a227be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjg3MzksIm5iZiI6MTczNDkyODQzOSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NTY0OS03ZjBkY2U0ZC1lYTE4LTQ4MGItOTQyMC01NDA1MzhhMjI3YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDQzMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM2ODZmZDE4ZmIyOWU2NTMwZjI5NDE1MTdiYmEwNmQ4MDBlYmIyNmUwZjVlYzcyMWU5YTM1NjdiZWZkNGU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.R91cQ9K-y07-9Bs2ZuOgTt7nRo5rS4g6sJWYZlL5mHM)
> 3. 转至目录 -> MacOS
> 4. 将文件拖放`deskflow`到辅助功能设置窗口（在步骤 1 中打开）
> 5. 启用两个 deskflow 选项
> 
> ![图像](https://private-user-images.githubusercontent.com/2151317/383996303-081f156a-e702-457c-922e-1fddf3648a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjg3MzksIm5iZiI6MTczNDkyODQzOSwicGF0aCI6Ii8yMTUxMzE3LzM4Mzk5NjMwMy0wODFmMTU2YS1lNzAyLTQ1N2MtOTIyZS0xZmRkZjM2NDhhNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDQzMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU5YWYzNDEwNDE0MmNmN2RkNTY3OTY2YWY0MmJiMzdjZmRkMDBhYzNiYmVjMzYxNjA1ODM5M2I2Yzk2OWU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DvPjNXqRaU6d9SjPZslQUmlPb_eBMTfOTI06xjGGoeE)

It's very useful to me
