### ISSUE TITLE
Printer Sharing Between Computer 

### ISSUE THREAD

**Issue by Slient1802** [deskflow/deskflow#7881]
### Feature Request

By sharing a single printer #801, multiple computers can work together to achieve greater efficiency and productivity than sending individually. Fewer cables, more space. Print from any computer to one shared printer.

**Comment by sithlord48** [comment]
This is way outside the scope of this project and your OS can already do this . No reason for us to add a feature for it.

**Comment by nbolton** [comment]
Nice idea for a new app though!
