### ISSUE TITLE
Ubuntu binaries not available for 1.17.1

### ISSUE THREAD

**Issue by the-rexmundi** [deskflow/deskflow#7882]
### Project

Deskflow

### Deskflow version number

1.17.1

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Ubuntu 24.04

### Deskflow configuration

MacOS 12 Server
Ubuntu 24.04 client
Windows 11 client

### What steps will reproduce the problem?

1.  Browser to https://github.com/deskflow/deskflow/releases/tag/v1.17.1
2. Open 'Assets'
3.  No Ubuntu binaries are linked

### Additional information

Ubuntu packages were available for 1.17,  are they meant to be available for 1.17.1.

Reviewed release notes and did not find a deprecation item.

**Comment by sithlord48** [comment]
Its not a bug ubuntu currently lacks the version of libportal we need to work correctly .

**Comment by nbolton** [comment]
See: #7884
