### ISSUE TITLE
Option to disable update check

### ISSUE THREAD

**Issue by fnpanic** [deskflow/deskflow#7890]
### Feature Request

Currently it looks like deskflow tries to reach cloudfront to check for updates. When the deskflow is run on a computer which blocks this, it seems like the connection does not work. When it can go out to cloudfront, there is no problem. The Address i see in the firewall is dll7xpq8c5ev0.cloudfront.net
Please add an option to disable the update check.
Thanks!

**Comment by sithlord48** [comment]
I think we should remove this update check and replace it with a link the user can click to see current releases. Users still have to go download the update. IMHO the update check is a nag screen.  
I also would argue the update check is only helpful to ppl not using package management . Mac os and Linux users are expected to use packages management and we have two package managers for windows so the group that finds this valuable I suspect to be a small group of deskflow users.

**Comment by sithlord48** [comment]
Turns out the value has a toggle it just was not exposed correctly so in #7892  i have added it into the Settings Dialog.

**Comment by nbolton** [comment]
> I suspect to be a small group of deskflow users.

80% of Synergy users are on Windows, and are likely to benefit greatly from an update check. The Deskflow download stats are likely to mirror this. I could do some analysis of the headers for those who opt-in to update check, but this would likely be a waste of time.

The pop only shows once at startup, so it's definitely not a nag.

**Comment by sithlord48** [comment]
After looking at the code I seen that.
