### ISSUE TITLE
Cursor shows at both server/client screen when server enables KDE 'Shake cursor to find it'

### ISSUE THREAD

**Issue by epiciskandar** [deskflow/deskflow#7894]
### Project

Deskflow

### Deskflow version number

1.18.0

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Fedora 41
- MacOS 14.7

### Deskflow configuration

- Fedora server
- MacOS Client
simple configuration, nothing special

### What steps will reproduce the problem?

1. move to client(MacOS) screen
2. 'Shake cursor to find it' is enabled on server side
3. shake mouse repeatly on client sceen, the enlarged cursor shakes on server screen too.

### Additional information

I think this is likely be the KDE input capture's bug?

**Comment by sithlord48** [comment]
if you think its a kde bug report it on the KDE bug tracker.

**Comment by nbolton** [comment]
> if you think its a kde bug report it on the KDE bug tracker.

Once you've reported it on the KDE tracker, please share the link here so others can find it easily :slightly_smiling_face:
