### ISSUE TITLE
1.17.2 breaks deskflow with MacOS client

### ISSUE THREAD

**Issue by rodalpho** [deskflow/deskflow#7906]
### Project

Deskflow

### Deskflow version number

1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [X] I am unable to try the latest continuous build

### OS versions/distros

Win11 latest
macos latest (patched today)

### Deskflow configuration

Win11 server on right, macos client on left

### What steps will reproduce the problem?

Updated both mac and windows to 1.17.2. Changed *NOTHING*. When I move my mouse to the left, it does not show up on the MacOS screen. Says "WARNING: cursor may not be visible", which is indeed accurate.

### Log output
Error on the client:

ERROR: failed to create quartz event tap

### Additional information

Looks like input-leap has the same problem. Did you pull changes from them maybe? If so they need to be reverted on MacOS at least.

https://github.com/input-leap/input-leap/issues/2073

**Comment by rodalpho** [comment]
Edit: Even though I had permitted both deskflow entries in privacy and security|accessibility, I needed to remove both entries, restart deskflow, enable it again, then restart again. This fixed the issue. Thanks, Apple!

**Comment by KinglyWayne** [comment]
https://github.com/debauchee/barrier/issues/1860#issuecomment-2480526740
This worked for me

**Comment by sithlord48** [comment]
This seams to be a long standing issue with mac os and it correctly updating permissions for upgraded applications that require accessibility permissions.

To future visitors solution is in our [wiki](https://github.com/deskflow/deskflow/wiki/Workarounds#macOS-accessibility-access) .

**Comment by rodalpho** [comment]
@sithlord48 Suggest noting that you may need to remove and re-add permissions upon upgrade. That stumped me for a bit.
