### ISSUE TITLE
macOS Sequoia 15.0.1 cannot switch input method language

### ISSUE THREAD

**Issue by rugalzhang** [deskflow/deskflow#7910]
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows 11
- macOS 15.0.1

### Deskflow configuration

- Windows 11 server, macOS client
- Windows has a single monitor，MacBook has it‘s own monitor and a external monitor
- Windows on the right， Mac on the left， while external monitor above MacBook

### What steps will reproduce the problem?

1. Start Deskflow on both computers
2. Mac connect to windows

### Log output

```shell
[2024-11-21T12:36:29] INFO: connected to secure socket
[2024-11-21T12:36:29] INFO: server tls certificate info: /CN=Deskflow
[2024-11-21T12:36:29] INFO: network encryption protocol: TLSv1.3
[2024-11-21T12:36:29] INFO: local languages: en
[2024-11-21T12:36:29] INFO: remote languages: zh
[2024-11-21T12:36:29] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: zh
[2024-11-21T12:36:29] NOTE: connected to server
[2024-11-21T12:36:31] INFO: entering screen
[2024-11-21T12:36:31] INFO: clipboard was updated
[2024-11-21T12:36:31] INFO: clipboard was updated
[2024-11-21T12:36:48] WARNING: current server language is not installed on client
```

### Additional information

both windows and Mac install rime input method
and as client，Mac already set language to zh
but cannot switch to Chinese input
while tap shift key，a warn log report，said “WARNING: current server language is not installed on client”

zh language setting as below
<img width="694" alt="Snipaste_2024-11-21_12-42-32" src="https://github.com/user-attachments/assets/db4503f6-3c87-46aa-bea8-cad52673309c">

**Comment by sithlord48** [comment]
[2024-11-21T12:36:29] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: zh

Can you confirm you confirm that both machines have chinese input . The log says only your server is only english.

**Comment by RikkaW** [comment]
@sithlord48 I have the same issue, macOS client and Windows server, both of them have Chinese language installed. As the screenshot above, it is already in Chinese language.

After some code search, I belive that it is simply because of `getKeyboardLayoutList` is broken on macOS. But I can't do more, since I don't have any development skill under Apple's world.

Btw, Synergy 3 works well, I'm switing to deskflow because clipboard sync always borken ramdomly.

**Comment by RikkaW** [comment]
@sithlord48 Wait a minute..

https://github.com/deskflow/deskflow/blob/f11178327d0f96de9813d9f0a62439b8279ab27b/src/lib/deskflow/unix/AppUtilUnix.cpp#L75-L93

https://github.com/deskflow/deskflow/blob/f11178327d0f96de9813d9f0a62439b8279ab27b/src/lib/deskflow/unix/AppUtilUnix.cpp#L91-L92

Seems it will always return only one language?

**Comment by sithlord48** [comment]
Feel free to make patches , there is alot of code that needs to be updated.

**Comment by RikkaW** [comment]
@sithlord48 I'm not able to test it :(

**Comment by sithlord48** [comment]
i don't have a way to test either but we can always ask those affected to test for us.

**Comment by RikkaW** [comment]
I mean I don't have enough free time to setup the build enviroment on macOS and try to build it. I can test if it works if can build it.

**Comment by RikkaW** [comment]
Synergy 3.0.80.1-rc3 has the same warnning, but no IME issue. Maybe there are other reasons?

```
synergy-core [2024-11-25T01:08:41] - INFO - local languages: en
synergy-core [2024-11-25T01:08:41] - INFO - remote languages: zh, en
synergy-core [2024-11-25T01:08:41] - WARNING - You need to install these languages on this computer and restart Synergy to enable support for multiple languages: zh
```

**Comment by rugalzhang** [comment]
> [2024-11-21T12:36:29] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: zh
> 
> Can you confirm you confirm that both machines have chinese input . The log says only your server is only english.

sorry for replying later, here's my input method, both server and client use [rime](https://rime.im/)

windows, as server
![Snipaste_2024-11-25_09-49-51](https://github.com/user-attachments/assets/771b2019-3a81-4927-a53b-6d8e1b2166ee)

macos, as client
<img width="1168" alt="Snipaste_2024-11-25_09-55-01" src="https://github.com/user-attachments/assets/84a3050b-b236-4b44-9a1e-811f9aa4bd24">

and the log came from mac client,  it says local(mac) en, remote(windows) zh, as my understander, it believes win server has chinese input and mac client do not, so maybe something wrong with mac?


btw, when checked input method on mac client, i noticed some different among thoese input methods about keyboard layout
as below,  while left system input method shows it's keyboard layout normally,  rime, on the right, says keyboard layout not available, wonder if it matters
<img width="1010" alt="Snipaste_2024-11-25_10-06-50" src="https://github.com/user-attachments/assets/d3b69bde-f05b-4f8f-a0c9-a558571b4ba9">

**Comment by sithlord48** [comment]
Yes  that matters you should try to resolve that first.

**Comment by SenorToru** [comment]
I've encountered a similar issue with Deskflow. On my setup, the macOS is the server and the Windows 10 laptop is the client. 
I'm using RIME for Chinese (Simplified & Traditional), English, and Japanese input methods on both Windows and macOS. 
Everything works as expected on the server (macOS) side, but on the client (Windows 10) side, when I switch to RIME or JP input methods and press any key on the keyboard, the input method automatically switches back to English.

To resolve this issue, I tried the following:

1. Open the Preferences page.
2. Go to the Regular page.
3. Uncheck the option "Use server's keyboard language on this computer (client mode)".
4. Save the setting and try it again.

After making this change, both the server and client sides are working fine now.

![image](https://github.com/user-attachments/assets/5ab2bba7-0ff0-4181-ba85-3f1c81341688)

**Comment by sithlord48** [comment]
^ Thanks @nbolton  Consider adding this to the wiki

**Comment by nbolton** [comment]
> To resolve this issue, I tried the following:
> 
> 1. Open the Preferences page.
> 2. Go to the Regular page.
> 3. Uncheck the option "Use server's keyboard language on this computer (client mode)".
> 4. Save the setting and try it again.
> 
> After making this change, both the server and client sides are working fine now.

I added this to the wiki, does it make sense?
https://github.com/deskflow/deskflow/wiki/Workarounds#Input-method-mismatch
