### ISSUE TITLE
Inconsistent GitHub artifact filename (contains flatpak file)

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7911]
### Project

Deskflow

### Deskflow version number

1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### What steps will reproduce the problem?

One of these things is not like the others. One of these things contains a flatpak file (`deskflow-continuous-x86_64-x86_64.zip`).

<img width="709" alt="Screenshot 2024-11-21 at 14 23 07" src="https://github.com/user-attachments/assets/048273ed-adf2-426b-8829-eca1adffeb42">

**Comment by sithlord48** [comment]
those are not meant to be touched by anyone and the names don't matter for our jobs only `package-deskflow` . This is resolved anyway by #7909  but i can do it also without building arm if we dont' land that .

**Comment by sithlord48** [comment]
The artifact `deskflow-version`x86_64-x86_64` is what happens when we let the flatpak builder upload on its own, that part is already fixed by #7908
