### ISSUE TITLE
arch/manjaro fails to load qt6.8 not found

### ISSUE THREAD

**Issue by albjeremias** [deskflow/deskflow#7916]
### Project

Deskflow

### Deskflow version number

v1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

manjaro

### Log output

```shell
$ deskflow
deskflow: /usr/lib/libQt6Core.so.6: version `Qt_6.8' not found (required by deskflow)
```

**Comment by sithlord48** [comment]
manjaro is not arch DO NOT use the arch package on manjaro

**Comment by nbolton** [comment]
> Seams that manjaro does not have qt 6.8.

Interesting, I thought Manjaro had package parity. TIL.
