### ISSUE TITLE
Desktopflow doesn't start in windows 7

### ISSUE THREAD

**Issue by ibonomik** [deskflow/deskflow#7917]
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [X] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Debian 12 is my main machine. And on another one I have got windows 7.

### What steps will reproduce the problem?

Start desktop problem: Set up from .msi is ok. But program cannot start. I get this error: “The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll.” 
Reason I know is windows 7 is old. Checked this page: https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_3/nf-dxgi1_3-createdxgifactory2 . There it is said "Minimum supported client - Windows 8.1 [desktop apps | UWP apps]"  

### Additional information

In win 7: Barrier 2.4.0 is working fine and it can communicate with Deskflow-1.17.2 in debian 12. 
I tried InputLeap-3.0.2 and I have got the same error message.
So I need a compatible release with win 7.
I put this point as issue instead of a request, because you don't say which windows It works. So, I thought it would work and I tried.   :)

**Comment by sithlord48** [comment]
Windows 10+ is required , its recommended to use barrier for windows 7  in this case.
