### ISSUE TITLE
1.17.2.0 install failed on ubuntu 24.04 

### ISSUE THREAD

**Issue by zhanglongqi** [deskflow/deskflow#7923]
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

ubuntu 24.04 
![image](https://github.com/user-attachments/assets/691bb39a-ddd7-40ce-823b-bf6c6a0ecb29)

**Comment by zhanglongqi** [comment]
I use `flatpak` instead. and it is working now.

**Comment by sithlord48** [comment]
ubuntu does not have the correct version of lib portal . on ubuntu (even thru a flatpak) on wayland you can only be a client .

**Comment by nbolton** [comment]
You need to use 1.17.0 for Ubuntu as it has libportal 0.8 static linked:
https://github.com/deskflow/deskflow/releases/tag/v1.17.0

**Comment by sithlord48** [comment]
> You need to use 1.17.0 for Ubuntu as it has libportal 0.8 static linked: https://github.com/deskflow/deskflow/releases/tag/v1.17.0

Don't do that instead use the flatpak
