### ISSUE TITLE
Cursor is no longer able to move on the client side after the 1.17.2 upgrade

### ISSUE THREAD

**Issue by Dentrax** [deskflow/deskflow#7928]
### Project

Deskflow

### Deskflow version number

1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [X] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.1.1

### Deskflow configuration

- Default

### What steps will reproduce the problem?

Move cursor from server to client.

### Log output

```shell
INFO: switch from "Furkans-MacBook-1.local" to "Furkans-MacBook-2.local" at -1920,413
INFO: leaving screen
WARNING: cursor may not be visible
```

### Additional information

* Started to happen after 1.17.0 to 1.17.2 upgrade
* On client logs, i can see the `INFO: entering screen` log (no other logs)
* I can't able to move the mouse on the client (but it becomes visible)
* Both running macOS 15.1.1

Any thoughts how can I debug this?

**Comment by sithlord48** [comment]
Check the permissions are set correctly , this seams to be a common issue with mac os upgrades.

**Comment by Dentrax** [comment]
Ensured that, on both server and client, all _Accessibility_ permissions have been allowed.

![image](https://github.com/user-attachments/assets/0247afd8-69f9-46b6-86bc-5b32cd7082ea)

**Comment by sithlord48** [comment]
that is problem you need to remove them all and let the application re add itself. The problem is they show as active but do not really get the access

**Comment by Dentrax** [comment]
Thank you! I removed every `deskflow.*` apps here on both server and client PCs, and re-adding those fixed the issue!

Could you please document a new "Upgrade" section in the wiki? https://github.com/deskflow/deskflow/wiki/Running-on-macOS

**Comment by nbolton** [comment]
> Could you please document a new "Upgrade" section in the wiki?

Done, do you think that it's clear enough?

> ✅ _For new app installs:_ The macOS 15 Sequoia firewall and security problems have now been fixed by Apple in the 15.1 minor update (not to be confused with 15.0.1 patch). Please update to 15.1 to solve the firewall and security problems.

> :warning: _When updating an app:_ You will need to remove the app from the macOS 15 Sequoia firewall settings, and re-add it for the new app update to be allowed.

**Comment by FAAAAT** [comment]
Hi guys, how could I remove deskflow completely? I removed the Deskflow dmg to trash and reinstall it, that doesn't work.

**Comment by nbolton** [comment]
> Hi guys, how could I remove deskflow completely? I removed the Deskflow.app to trash and reinstall it, that doesn't work.

Would you mind creating a new discussion?
