### ISSUE TITLE
core server binary does not exist

### ISSUE THREAD

**Issue by jiapei100** [deskflow/deskflow#7937]
### Project

Deskflow

### Deskflow version number

1.17.2.16

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [X] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Ubuntu 24.04.1

### Deskflow configuration

- Windows 11 Left Client, Ubuntu 24.04.1 Server

### What steps will reproduce the problem?

1. Just Start Deskflow on Ubuntu 24.01 Server

### Log output

```zsh
➜  ~ deskflow --debug
[2024-12-02T21:23:51] INFO: Deskflow v1.17.2.16
[2024-12-02T21:23:51] INFO: no .env file in dir: /home/lvision
[2024-12-02T21:23:51] INFO: no .env file in app config dir: /home/lvision/.config/Deskflow
[2024-12-02T21:23:51] INFO: starting core server process (desktop mode)
[2024-12-02T21:23:51] FATAL: core server binary does not exist
version check server success, http status: 200
version check response: 1.17.2
no updates found
saving window size and position
emitting config saving signal
committing app config
committing server config
writing config to filesystem
[1]    10612 IOT instruction (core dumped)  deskflow --debug
➜  ~ 
```

### Additional information

![Deskflow Error](https://longervision.com/deskflow_error.png)

**Comment by nbolton** [comment]
> Local developer build (built it myself)

Please let me know what's in your `build/bin` dir.

**Comment by jiapei100** [comment]
Hi, @nbolton 

```
➜  bin git:(master) ✗ ll
total 12M
4.0K drwxrwxr-x  2 lvision lvision 4.0K Dec  2 20:50 ./
4.0K drwxrwxr-x 10 lvision lvision 4.0K Dec  2 21:00 ../
1.1M -rwxrwxr-x  1 lvision lvision 1.1M Dec  2 20:50 deskflow*
1.9M -rwxrwxr-x  1 lvision lvision 1.9M Dec  2 20:50 deskflow-core*
2.4M -rwxrwxr-x  1 lvision lvision 2.4M Dec  2 20:50 integtests*
6.4M -rwxrwxr-x  1 lvision lvision 6.4M Dec  2 20:50 unittests*
```

**Comment by nbolton** [comment]
Looks like maybe you enabled `BUILD_UNIFIED` CMake option. Is that correct? This is off by default.

**Comment by jiapei100** [comment]
@nbolton 

Thank you so much ... Problem solved.  I did turn on `BUILD_UNIFIED`. Thank you ...

**Comment by nbolton** [comment]
> Thank you so much ... Problem solved. I did turn on `BUILD_UNIFIED`. Thank you ...

No problem, yeah the GUI doesn't support that yet. It's a valid case so I raised an issue: #7951
