### ISSUE TITLE
Too many arguments error shows `%s` instead of option name

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7942]
### Project

Deskflow

### Deskflow version number

deskflow-1.17.2.16

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### OS versions/distros

Fedora 41

### What steps will reproduce the problem?

Add a extra arg to config option, e.g.
```
section: options
	protocol = barrier,foo
```

### Log output

`[2024-12-04T14:17:55] ERROR: cannot read configuration "/home/nick/.config/Deskflow/deskflow-server.conf": read error: line 49: to many arguments to %s
        /home/nick/Projects/deskflow/src/lib/deskflow/ServerApp.cpp:257`

### Additional information

`%s` is not replaced by string

**Comment by sithlord48** [comment]
When i try todo this the file is cleaned and i don't see the error can you confirm this please.
