### ISSUE TITLE
Creating a fake screen in order for Qt not to crash

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7963]
### Project

Deskflow

### Deskflow version number

1.17.2.52

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### OS versions/distros

Fedora 41 (Wayland with Qt 6.8.0)

### What steps will reproduce the problem?

1. ?

Expected: Server shares until I stop the process
Actual: Info message from Qt(?) and sharing stops

### Log output

```shell
[2024-12-09T13:14:35] INFO: Creating a fake screen in order for Qt not to crash
```

### Additional information

This seems like a hack in Qt. Maybe the new fake screen confuses Deskflow server process?

**Comment by nbolton** [comment]
@sithlord48 Seen this one yet?

**Comment by sithlord48** [comment]
nope

**Comment by sithlord48** [comment]
Either way i don't think this is our bug I suspect its more the platform not correctly releasing and prompting for permission again.

**Comment by nbolton** [comment]
Yeah, not our bug.
