### ISSUE TITLE
Moving the mouse from Windows to Mac, the mouse moves slightly faster and seems to float. Most likely, it will be in the top middle of the screen

### ISSUE THREAD

**Issue by DearZack** [deskflow/deskflow#7966]
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows11
- macos 14.6

**Comment by sean5446** [comment]
You can try to adjust the speed of the mouse on Mac in:
System Settings > Accessibility > Pointer Control > Mouse Options...

**Comment by fourk0** [comment]
this issue is not solved, the problem still persists (changing the mouse scaling doesn't help, it only changes the mac touchpad speed, not the speed at which the mac cursor moves when controlled by the mouse from windows)

**Comment by sithlord48** [comment]
This is solved by setting the Mouse Scaling var in deskflow (not what that link describes)  we just don't do great job of exposing that yet.  #8207  will fix the expose part.
