### ISSUE TITLE
install error in OSX10.15.7 

### ISSUE THREAD

**Issue by qajknsdjaks** [deskflow/deskflow#7969]
### Project

Deskflow

### Deskflow version number

1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

osx 10.15.7

**Comment by sithlord48** [comment]
Can you describe what happened and what you have tried ?

**Comment by qajknsdjaks** [comment]
> Can you describe what happened and what you have tried ?

![截屏20241214213019](https://github.com/user-attachments/assets/e9ba266b-0124-4842-b073-754fd3e45c35)

Please provide support for my operating system

**Comment by sithlord48** [comment]
Ah well your version of mac os is too Old to use the Application. You will need to install mac os 12 or higher.

**Comment by shivshankar3578** [comment]
WTF what is the sense to support it macOS Monterey or later while better inbuild feature there. 
make it compatible to osx at least for Catalina.

**Comment by sithlord48** [comment]
You cant use our GUi with older then mac os 12.

**Comment by nbolton** [comment]
> make it compatible to osx at least for Catalina.

Catalina was EOL by Apple on November 30, 2022.

Feel free to use older versions of Synergy or Barrier, which support Catalina and are both compatible with Deskflow.
