### ISSUE TITLE
MacOS 10.14 support?

### ISSUE THREAD

**Issue by AmigaAbattoir** [deskflow/deskflow#7973]
### Feature Request

What is the minimum supported MacOS version? Are there any plans on keeping older versions of Mac OS supported? I have an old Mac running 10.14, but the x86_64 release 1.17.2 doesn't run on it.

**Comment by AmigaAbattoir** [comment]
Just saw the pull request *chore: Add minimum macOS version to readme*. 

Would it be possible to run an older version of Synergy to connect to Deskflow if it's in Synergy mode? Or would it be possible to build on an older version of MacOS?

**Comment by sithlord48** [comment]
Not with the gui
