### ISSUE TITLE
deskflow icon keep duplicating on the dock macOS

### ISSUE THREAD

**Issue by KarrixLee** [deskflow/deskflow#7974]
### Project

Deskflow

### Deskflow version number

1.17.2.0 (9084a490)

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.2 

### What steps will reproduce the problem?

when it is reconnecting, it will keep duplicating the icon on the docker
![CleanShot 2024-12-16 at 12 03 41@2x](https://github.com/user-attachments/assets/d55a9bee-911d-41ce-bee9-1202fe85d9fd)

**Comment by sithlord48** [comment]
I am going to hyjack your issue. For the root cause of this

**Comment by WajahatAliShah1** [comment]
Running into this error on deskflow 

Deskflow: 1.26.0.0 (760e3b99)
Qt: 6.10.1
System: macOS Tahoe (26.5.2)
