### ISSUE TITLE
Tray icon not visible with Wayland GNOME 4x

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7978]
### Project

Deskflow

### Deskflow version number

1.17.2.54

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### OS versions/distros

Fedora 41 with Wayland and [Tray Icons Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded)

### What steps will reproduce the problem?

1. Use GNOME 47.2 with Wayland
1. Install [Tray Icons Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded)
2. Start Deskflow GUI

Expect: Tray icon
Actual: No tray icon (only other apps)

![image](https://github.com/user-attachments/assets/bde66c0c-a1ed-4c11-af0b-a798fd1c87bb)

Workaround: Use Xorg

**Comment by sithlord48** [comment]
Was this working before this version of gnome ? do you need an extension for this support in gnome ?

**Comment by sithlord48** [comment]
the Extension you are using says it only supports X11 apps.
Try this https://extensions.gnome.org/extension/615/appindicator-support/ one please and report back

**Comment by sithlord48** [comment]
Documented this here https://github.com/deskflow/deskflow/wiki/Workarounds#GNOME-is-missing-tray-icons
