### ISSUE TITLE
Move .vscode dir to separate repo

### ISSUE THREAD

**Issue by nbolton** [deskflow/deskflow#7979]
### Feature Request

The `.vscode` dir contains useful things for VS Code users but having it in the project signals a bias and that there might be a recommendation/requirement to use it (which there is not).

Remove the `.vscode` dir and host it in a separate repo, such as `deskflow-dot-vscode`

**Comment by sithlord48** [comment]
how about `deskflow-dev-support` and you can move all the dev type help things here so ppl can choose what they may need for their set up

**Comment by sithlord48** [comment]
Created a new [repo](https://www.github.com/deskflow/.vscode) . Will link a commit to remove it from this repo
