### ISSUE TITLE
Deskflow.app is damaged

### ISSUE THREAD

**Issue by r4nchy** [deskflow/deskflow#7983]
### Project

Deskflow

### Deskflow version number

1.17.2

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.1

### Deskflow configuration

App doesn't even install

### What steps will reproduce the problem?

Installing Deskflow in macOS

### Additional information

I have used previous builds of synergy and it had worked fine. It seems the .dmg file in release page is damaged and not made properly

**Comment by 1itt1eB0y** [comment]
Warning: No available formula with the name "deskflow".
==> Searching for similarly named formulae and casks...
==> Casks
desktoppr

To install desktoppr, run:
  brew install --cask desktoppr

**Comment by sithlord48** [comment]
You need to add our homebrew tap to install from homebrew
