### ISSUE TITLE
Allow disabling warnings when keyboard layout is unknown

### ISSUE THREAD

**Issue by sersorrel** [deskflow/deskflow#7996]
### Feature Request

I use a custom keyboard layout on my Linux server. Unfortunately this means I get two separate warnings logged on every keypress:

```
[2024-12-20T14:45:28] WARNING: language "gb-qw0rty" is unknown
[2024-12-20T14:45:28] WARNING: failed to convert layout lang code: "gb-qw0rty"
```

Is there any way to disable these warnings? Or to make them show up once on startup, rather than every single time I press a key? Disabling "Use server's keyboard language" on the client doesn't appear to help.

**Comment by sithlord48** [comment]
well in this case i would have to agree as `gb-qw0rty` is one i have never heard of . usually its just "" but yes the message is annoying and no there is not currently a way to disable them other then change the log level , they should be moved it anything to debug1 level and that would at least not show them for general info

**Comment by sithlord48** [comment]
lets tag @nbolton  he would know more about the logging levels. This one currently is `WARN` and these are shown at all levels.

**Comment by nbolton** [comment]
Yeah, it should be a one time message; the warn log line needs to be moved to an init function if possible.

**Comment by sithlord48** [comment]
Great news I no longer see this error :D 

My linux DE info is:

`Plasma: 6.2.4`
`KDE Frameworks: 6.9.0`

Should resolve for others in time.

**Comment by sersorrel** [comment]
I will admit I haven't had a chance to test this again since your comment, but I don't see any way this could have disappeared apart from your keyboard configuration changing. `X11LayoutsParser.cpp` hasn't changed in the last two months (so the log is still emitted on every call of `X11LayoutsParser::convertLayotToISO()`), and `Server::handleKeyDownEvent()` still calls `AppUtil::instance().getCurrentLanguageCode()` (which calls `X11LayoutsParser::convertLayotToISO()`) and `AppUtilUnix.cpp` hasn't changed in a month either.

I'll shout if it's still happening in the new year.
